//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.TaskExecutor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResBindingCostPerRunStep {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResBindingCostPerRunStep() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.TaskExecutor.ResBindingCostPerRunStep", typeof(ResBindingCostPerRunStep).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costo allestimento.
        /// </summary>
        public static string BindingCost {
            get {
                return ResourceManager.GetString("BindingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostPerUnit12 {
            get {
                return ResourceManager.GetString("CostPerUnit12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostPerUnit16 {
            get {
                return ResourceManager.GetString("CostPerUnit16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostPerUnit24 {
            get {
                return ResourceManager.GetString("CostPerUnit24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostPerUnit32 {
            get {
                return ResourceManager.GetString("CostPerUnit32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostPerUnit4 {
            get {
                return ResourceManager.GetString("CostPerUnit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostPerUnit6 {
            get {
                return ResourceManager.GetString("CostPerUnit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostPerUnit8 {
            get {
                return ResourceManager.GetString("CostPerUnit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string StartingCost12 {
            get {
                return ResourceManager.GetString("StartingCost12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string StartingCost16 {
            get {
                return ResourceManager.GetString("StartingCost16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string StartingCost24 {
            get {
                return ResourceManager.GetString("StartingCost24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string StartingCost32 {
            get {
                return ResourceManager.GetString("StartingCost32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string StartingCost4 {
            get {
                return ResourceManager.GetString("StartingCost4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string StartingCost6 {
            get {
                return ResourceManager.GetString("StartingCost6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string StartingCost8 {
            get {
                return ResourceManager.GetString("StartingCost8", resourceCulture);
            }
        }
    }
}
