//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.TaskExecutor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResFlexo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResFlexo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.TaskExecutor.ResFlexo", typeof(ResFlexo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo impanto / mq.
        /// </summary>
        public static string CostImplant {
            get {
                return ResourceManager.GetString("CostImplant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indicare un costo di impnto al mq.
        /// </summary>
        public static string CostImplantToolTip {
            get {
                return ResourceManager.GetString("CostImplantToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarto (mt).
        /// </summary>
        public static string PaperFirstStartLenght {
            get {
                return ResourceManager.GetString("PaperFirstStartLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica i metri di scarto in avviamento.
        /// </summary>
        public static string PaperFirstStartLenghtToolTip {
            get {
                return ResourceManager.GetString("PaperFirstStartLenghtToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarto succ. (mt).
        /// </summary>
        public static string PaperSecondStartLenght {
            get {
                return ResourceManager.GetString("PaperSecondStartLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica i metri di scarto in avviamento, per il cambio rotolo.
        /// </summary>
        public static string PaperSecondStartLenghtToolTip {
            get {
                return ResourceManager.GetString("PaperSecondStartLenghtToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilindri stampa.
        /// </summary>
        public static string PrintingUnit {
            get {
                return ResourceManager.GetString("PrintingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castelli di stampa della macchina da stampa.
        /// </summary>
        public static string PrintingUnitToolTip {
            get {
                return ResourceManager.GetString("PrintingUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larghezza (cm).
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larghezza massima della bobina.
        /// </summary>
        public static string WidthToolTip {
            get {
                return ResourceManager.GetString("WidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Metrico.
        /// </summary>
        public static string ZMetric {
            get {
                return ResourceManager.GetString("ZMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z esprime il diametro in mm.
        /// </summary>
        public static string ZMetricToolTip {
            get {
                return ResourceManager.GetString("ZMetricToolTip", resourceCulture);
            }
        }
    }
}
