//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.TaskExecutor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResLitho {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLitho() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.TaskExecutor.ResLitho", typeof(ResLitho).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo di cambio lastra.
        /// </summary>
        public static string ChangePlateTime {
            get {
                return ResourceManager.GetString("ChangePlateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il tempo per il cambio della lastra.
        /// </summary>
        public static string ChangePlateTimeToolTip {
            get {
                return ResourceManager.GetString("ChangePlateTimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castelli stampa.
        /// </summary>
        public static string PrintingUnit {
            get {
                return ResourceManager.GetString("PrintingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica i castelli di stampa.
        /// </summary>
        public static string PrintingUnitToolTip {
            get {
                return ResourceManager.GetString("PrintingUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversibile.
        /// </summary>
        public static string Sheetwise {
            get {
                return ResourceManager.GetString("Sheetwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversibile dal castello.
        /// </summary>
        public static string SheetwiseAfterPrintingUnit {
            get {
                return ResourceManager.GetString("SheetwiseAfterPrintingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica da quale castello in poi è possibile configurare la macchina come reversibile.
        /// </summary>
        public static string SheetwiseAfterPrintingUnitToolTip {
            get {
                return ResourceManager.GetString("SheetwiseAfterPrintingUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica se la macchina è reversibile.
        /// </summary>
        public static string SheetwiseToolTip {
            get {
                return ResourceManager.GetString("SheetwiseToolTip", resourceCulture);
            }
        }
    }
}
