//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.TaskExecutor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPlotterOnMq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPlotterOnMq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.TaskExecutor.ResPlotterOnMq", typeof(ResPlotterOnMq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglio-Costo Ml.
        /// </summary>
        public static string CostCutting {
            get {
                return ResourceManager.GetString("CostCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo del taglio al Metro lineare.
        /// </summary>
        public static string CostCuttingToolTip {
            get {
                return ResourceManager.GetString("CostCuttingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InkJet-Costo Mq (alta definizione).
        /// </summary>
        public static string CostInkJetHight {
            get {
                return ResourceManager.GetString("CostInkJetHight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo al mq quando si stampa a getto d&apos;inchiostro ad alta definizione.
        /// </summary>
        public static string CostInkJetHightToolTip {
            get {
                return ResourceManager.GetString("CostInkJetHightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InkJet-Costo Mq (bassa definizione).
        /// </summary>
        public static string CostInkJetLow {
            get {
                return ResourceManager.GetString("CostInkJetLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo al mq quando si stampa a getto d&apos;inchiostro a bassa definizione.
        /// </summary>
        public static string CostInkJetLowToolTip {
            get {
                return ResourceManager.GetString("CostInkJetLowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InkJet-Costo Mq (media definizione).
        /// </summary>
        public static string CostInkJetMed {
            get {
                return ResourceManager.GetString("CostInkJetMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo al mq quando si stampa a getto d&apos;inchiostro a media definizione.
        /// </summary>
        public static string CostInkJetMedToolTip {
            get {
                return ResourceManager.GetString("CostInkJetMedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV-Costo Mq (alta definizione).
        /// </summary>
        public static string CostUVHight {
            get {
                return ResourceManager.GetString("CostUVHight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo al mq quando si stampa UV ad alta definizione.
        /// </summary>
        public static string CostUVHightToolTip {
            get {
                return ResourceManager.GetString("CostUVHightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV-Costo Mq (bassa definizione).
        /// </summary>
        public static string CostUVLow {
            get {
                return ResourceManager.GetString("CostUVLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo al mq quando si stampa UV a bassa definizione.
        /// </summary>
        public static string CostUVLowToolTip {
            get {
                return ResourceManager.GetString("CostUVLowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV-Costo Mq (media definizione).
        /// </summary>
        public static string CostUVMed {
            get {
                return ResourceManager.GetString("CostUVMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo al mq quando si stampa UV a media definizione.
        /// </summary>
        public static string CostUVMedToolTip {
            get {
                return ResourceManager.GetString("CostUVMedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV-Costo Mq bianco.
        /// </summary>
        public static string CostWhite {
            get {
                return ResourceManager.GetString("CostWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo al mq del bianco quando si stampa su superfici non bianche.
        /// </summary>
        public static string CostWhiteToolTip {
            get {
                return ResourceManager.GetString("CostWhiteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo primo Avviamento.
        /// </summary>
        public static string StartingCost1 {
            get {
                return ResourceManager.GetString("StartingCost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo del primo avviamento.
        /// </summary>
        public static string StartingCost1ToolTip {
            get {
                return ResourceManager.GetString("StartingCost1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo Avviamenti successivi.
        /// </summary>
        public static string StartingCost2 {
            get {
                return ResourceManager.GetString("StartingCost2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo degli avviamenti successivi al primo.
        /// </summary>
        public static string StartingCost2ToolTip {
            get {
                return ResourceManager.GetString("StartingCost2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa costi copia scaglionati.
        /// </summary>
        public static string UseDifferentCostPerUnit {
            get {
                return ResourceManager.GetString("UseDifferentCostPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che è possibile usare costi copia per scaglioni di tiratura.
        /// </summary>
        public static string UseDifferentCostPerUnitToolTip {
            get {
                return ResourceManager.GetString("UseDifferentCostPerUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa penalizzazioni per grammatura.
        /// </summary>
        public static string UseDifferentDeficitOnCostForWeightStep {
            get {
                return ResourceManager.GetString("UseDifferentDeficitOnCostForWeightStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che è possibile usare penalizzazioni per grammature differenti.
        /// </summary>
        public static string UseDifferentDeficitOnCostForWeightStepToolTip {
            get {
                return ResourceManager.GetString("UseDifferentDeficitOnCostForWeightStepToolTip", resourceCulture);
            }
        }
    }
}
