//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.TaskExecutor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTaskEstimatedOnTime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTaskEstimatedOnTime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.TaskExecutor.ResTaskEstimatedOnTime", typeof(ResTaskEstimatedOnTime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media oraria.
        /// </summary>
        public static string AvarageRunPerHour {
            get {
                return ResourceManager.GetString("AvarageRunPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica la tiratura media oraria.
        /// </summary>
        public static string AvarageRunPerHourToolTip {
            get {
                return ResourceManager.GetString("AvarageRunPerHourToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo all&apos;ora (tiratura).
        /// </summary>
        public static string CostPerHourRunning {
            get {
                return ResourceManager.GetString("CostPerHourRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo orario della lavorazione/macchina.
        /// </summary>
        public static string CostPerHourRunningToolTip {
            get {
                return ResourceManager.GetString("CostPerHourRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo all&apos;ora (avviamento).
        /// </summary>
        public static string CostPerHourStarting {
            get {
                return ResourceManager.GetString("CostPerHourStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo orario in avviamento.
        /// </summary>
        public static string CostPerHourStartingToolTip {
            get {
                return ResourceManager.GetString("CostPerHourStartingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo Avviamento.
        /// </summary>
        public static string StartingTime1 {
            get {
                return ResourceManager.GetString("StartingTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il tempo in mm:ss di avviamento.
        /// </summary>
        public static string StartingTime1ToolTip {
            get {
                return ResourceManager.GetString("StartingTime1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo Avviamenti Successivi.
        /// </summary>
        public static string StartingTime2 {
            get {
                return ResourceManager.GetString("StartingTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il tempo in mm:ss degli avviamenti successivi.
        /// </summary>
        public static string StartingTime2ToolTip {
            get {
                return ResourceManager.GetString("StartingTime2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo minimale.
        /// </summary>
        public static string TimeForfait {
            get {
                return ResourceManager.GetString("TimeForfait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il tempo minimo di lavorazione.
        /// </summary>
        public static string TimeForfaitToolTip {
            get {
                return ResourceManager.GetString("TimeForfaitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa penalizzazioni per grammatura.
        /// </summary>
        public static string UseDifferentDeficitForWeightStep {
            get {
                return ResourceManager.GetString("UseDifferentDeficitForWeightStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che è possibile differenziare le medie per grammatura di carta.
        /// </summary>
        public static string UseDifferentDeficitForWeightStepToolTip {
            get {
                return ResourceManager.GetString("UseDifferentDeficitForWeightStepToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa tirature orarie differenti per scaglioni di copie.
        /// </summary>
        public static string UseDifferentRunPerHour {
            get {
                return ResourceManager.GetString("UseDifferentRunPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che è possibile usare differenti medie orarie per scaglioni di copie.
        /// </summary>
        public static string UseDifferentRunPerHourToolTip {
            get {
                return ResourceManager.GetString("UseDifferentRunPerHourToolTip", resourceCulture);
            }
        }
    }
}
