//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.TaskExecutor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTaskEstimatedOn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTaskEstimatedOn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.TaskExecutor.ResTaskEstimatedOn", typeof(ResTaskEstimatedOn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CodTaskExecutor {
            get {
                return ResourceManager.GetString("CodTaskExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CodTaskExecutorOn {
            get {
                return ResourceManager.GetString("CodTaskExecutorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CodTaskExecutorOnToolTip {
            get {
                return ResourceManager.GetString("CodTaskExecutorOnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CodTaskExecutorToolTip {
            get {
                return ResourceManager.GetString("CodTaskExecutorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostForfait {
            get {
                return ResourceManager.GetString("CostForfait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostForfaitForSheet {
            get {
                return ResourceManager.GetString("CostForfaitForSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostForfaitForSheetToolTip {
            get {
                return ResourceManager.GetString("CostForfaitForSheetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string CostForfaitToolTip {
            get {
                return ResourceManager.GetString("CostForfaitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string steps {
            get {
                return ResourceManager.GetString("steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string stepsToolTip {
            get {
                return ResourceManager.GetString("stepsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string taskexecutors {
            get {
                return ResourceManager.GetString("taskexecutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string taskexecutorsToolTip {
            get {
                return ResourceManager.GetString("taskexecutorsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string TimeStampTable {
            get {
                return ResourceManager.GetString("TimeStampTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string TimeStampTableToolTip {
            get {
                return ResourceManager.GetString("TimeStampTableToolTip", resourceCulture);
            }
        }
    }
}
