//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.TaskExecutor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTaskEstimatedOnUnit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTaskEstimatedOnUnit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.TaskExecutor.ResTaskEstimatedOnUnit", typeof(ResTaskEstimatedOnUnit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo a copia.
        /// </summary>
        public static string CostPerUnit {
            get {
                return ResourceManager.GetString("CostPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo a passaggio.
        /// </summary>
        public static string CostPerUnitToolTip {
            get {
                return ResourceManager.GetString("CostPerUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo primo Avviamento.
        /// </summary>
        public static string StartingCost1 {
            get {
                return ResourceManager.GetString("StartingCost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo primo Avviamento B/N.
        /// </summary>
        public static string StartingCost1BW {
            get {
                return ResourceManager.GetString("StartingCost1BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; possibile specificare un costo di avviamento differente se la stampa è a Bianco e Nero.
        /// </summary>
        public static string StartingCost1BWToolTip {
            get {
                return ResourceManager.GetString("StartingCost1BWToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo del primo avviamento.
        /// </summary>
        public static string StartingCost1ToolTip {
            get {
                return ResourceManager.GetString("StartingCost1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo Avviamenti successivi.
        /// </summary>
        public static string StartingCost2 {
            get {
                return ResourceManager.GetString("StartingCost2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo Avviamenti successivi B/N.
        /// </summary>
        public static string StartingCost2BW {
            get {
                return ResourceManager.GetString("StartingCost2BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; possibile specificare un costo di avviamento differente se la stampa è a Bianco e Nero.
        /// </summary>
        public static string StartingCost2BWToolTip {
            get {
                return ResourceManager.GetString("StartingCost2BWToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il costo degli avviamenti successivi al primo.
        /// </summary>
        public static string StartingCost2ToolTip {
            get {
                return ResourceManager.GetString("StartingCost2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa costi copia scaglionati.
        /// </summary>
        public static string UseDifferentCostPerUnit {
            get {
                return ResourceManager.GetString("UseDifferentCostPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa costi copia scaglionati per B/N.
        /// </summary>
        public static string UseDifferentCostPerUnitBW {
            get {
                return ResourceManager.GetString("UseDifferentCostPerUnitBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che è possibile usare costi copia per scaglioni di tiratura.
        /// </summary>
        public static string UseDifferentCostPerUnitToolTip {
            get {
                return ResourceManager.GetString("UseDifferentCostPerUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che è possibile usare costi copia per scaglioni di tiratura quando la stampa è Bianco e Nero.
        /// </summary>
        public static string UseDifferentCostPerUnitToolTipBW {
            get {
                return ResourceManager.GetString("UseDifferentCostPerUnitToolTipBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa penalizzazioni per grammatura.
        /// </summary>
        public static string UseDifferentDeficitOnCostForWeightStep {
            get {
                return ResourceManager.GetString("UseDifferentDeficitOnCostForWeightStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che è possibile usare penalizzazioni per grammature differenti.
        /// </summary>
        public static string UseDifferentDeficitOnCostForWeightStepToolTip {
            get {
                return ResourceManager.GetString("UseDifferentDeficitOnCostForWeightStepToolTip", resourceCulture);
            }
        }
    }
}
