//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.TaskExecutor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTaskExecutor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTaskExecutor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.TaskExecutor.ResTaskExecutor", typeof(ResTaskExecutor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice.
        /// </summary>
        public static string CodTaskExecutor {
            get {
                return ResourceManager.GetString("CodTaskExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il codice autogenerato.
        /// </summary>
        public static string CodTaskExecutorToolTip {
            get {
                return ResourceManager.GetString("CodTaskExecutorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contropinza (cm).
        /// </summary>
        public static string ControPinza {
            get {
                return ResourceManager.GetString("ControPinza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica la contropinza in cm.
        /// </summary>
        public static string ControPinzaToolTip {
            get {
                return ResourceManager.GetString("ControPinzaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismessa.
        /// </summary>
        public static string Dismissed {
            get {
                return ResourceManager.GetString("Dismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che la macchina è stata dismessa.
        /// </summary>
        public static string DismissedToolTip {
            get {
                return ResourceManager.GetString("DismissedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato Massimo.
        /// </summary>
        public static string FormatMax {
            get {
                return ResourceManager.GetString("FormatMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato massimo della macchina.
        /// </summary>
        public static string FormatMaxToolTip {
            get {
                return ResourceManager.GetString("FormatMaxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato Minimo.
        /// </summary>
        public static string FormatMin {
            get {
                return ResourceManager.GetString("FormatMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato minimo della macchina.
        /// </summary>
        public static string FormatMinToolTip {
            get {
                return ResourceManager.GetString("FormatMinToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\d{1,4})((\,\d{0,5}){0,1})[xX](\d{1,4})((\,\d{0,5}){0,1})?$.
        /// </summary>
        public static string FormatValidation {
            get {
                return ResourceManager.GetString("FormatValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formato non valido (es. valido: 70x100).
        /// </summary>
        public static string FormatValidationError {
            get {
                return ResourceManager.GetString("FormatValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo in base ai Mq.
        /// </summary>
        public static string IsEstimatedOnMq {
            get {
                return ResourceManager.GetString("IsEstimatedOnMq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che il costo viene calcolato in base ai metri quadri del materiale lavorato.
        /// </summary>
        public static string IsEstimatedOnMqToolTip {
            get {
                return ResourceManager.GetString("IsEstimatedOnMqToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo a Copie.
        /// </summary>
        public static string IsEstimatedOnRun {
            get {
                return ResourceManager.GetString("IsEstimatedOnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che il costo viene calcolato in base alle copie.
        /// </summary>
        public static string IsEstimatedOnRunToolTip {
            get {
                return ResourceManager.GetString("IsEstimatedOnRunToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo a Tempo.
        /// </summary>
        public static string IsEstimatedOnTime {
            get {
                return ResourceManager.GetString("IsEstimatedOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica che il costo viene calcolato in base al tempo.
        /// </summary>
        public static string IsEstimatedOnTimeToolTip {
            get {
                return ResourceManager.GetString("IsEstimatedOnTimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laterale (cm).
        /// </summary>
        public static string Laterale {
            get {
                return ResourceManager.GetString("Laterale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica il laterale in cm.
        /// </summary>
        public static string LateraleToolTip {
            get {
                return ResourceManager.GetString("LateraleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinza (cm).
        /// </summary>
        public static string Pinza {
            get {
                return ResourceManager.GetString("Pinza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica la pinza in cm.
        /// </summary>
        public static string PinzaToolTip {
            get {
                return ResourceManager.GetString("PinzaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string SetTaskExecutorEstimatedOn {
            get {
                return ResourceManager.GetString("SetTaskExecutorEstimatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string SetTaskExecutorEstimatedOnToolTip {
            get {
                return ResourceManager.GetString("SetTaskExecutorEstimatedOnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome macchina.
        /// </summary>
        public static string TaskExecutorName {
            get {
                return ResourceManager.GetString("TaskExecutorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome della macchina o chi esegue una lavorazione.
        /// </summary>
        public static string TaskExecutorNameToolTip {
            get {
                return ResourceManager.GetString("TaskExecutorNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string TimeStampTable {
            get {
                return ResourceManager.GetString("TimeStampTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxxxxx.
        /// </summary>
        public static string TimeStampTableToolTip {
            get {
                return ResourceManager.GetString("TimeStampTableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica la versione della macchina.
        /// </summary>
        public static string VersionToolTip {
            get {
                return ResourceManager.GetString("VersionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr/mq massima.
        /// </summary>
        public static string WeightMax {
            get {
                return ResourceManager.GetString("WeightMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica la massima grammatura ammissibile.
        /// </summary>
        public static string WeightMaxToolTip {
            get {
                return ResourceManager.GetString("WeightMaxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr/mq minima.
        /// </summary>
        public static string WeightMin {
            get {
                return ResourceManager.GetString("WeightMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica la minima grammatura ammissibile.
        /// </summary>
        public static string WeightMinToolTip {
            get {
                return ResourceManager.GetString("WeightMinToolTip", resourceCulture);
            }
        }
    }
}
