//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResProductTask {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResProductTask() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.Products.ResProductTask", typeof(ResProductTask).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice del prodotto.
        /// </summary>
        public static string CodProduct {
            get {
                return ResourceManager.GetString("CodProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string CodProductTask {
            get {
                return ResourceManager.GetString("CodProductTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string CodProductTaskToolTip {
            get {
                return ResourceManager.GetString("CodProductTaskToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice del prodotto.
        /// </summary>
        public static string CodProductToolTip {
            get {
                return ResourceManager.GetString("CodProductToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavorazione nascosta.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavorazione nascosta.
        /// </summary>
        public static string HiddenToolTip {
            get {
                return ResourceManager.GetString("HiddenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string IndexOf {
            get {
                return ResourceManager.GetString("IndexOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string IndexOfToolTip {
            get {
                return ResourceManager.GetString("IndexOfToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotto.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte lavorazione.
        /// </summary>
        public static string ProductPartTasks {
            get {
                return ResourceManager.GetString("ProductPartTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte lavorazione.
        /// </summary>
        public static string ProductPartTasksToolTip {
            get {
                return ResourceManager.GetString("ProductPartTasksToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavorazione.
        /// </summary>
        public static string ProductTaskName {
            get {
                return ResourceManager.GetString("ProductTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavorazione.
        /// </summary>
        public static string ProductTaskNameToolTip {
            get {
                return ResourceManager.GetString("ProductTaskNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotto.
        /// </summary>
        public static string ProductToolTip {
            get {
                return ResourceManager.GetString("ProductToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selettore lavorazione.
        /// </summary>
        public static string SelectorProductTask {
            get {
                return ResourceManager.GetString("SelectorProductTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selettore lavorazione.
        /// </summary>
        public static string SelectorProductTaskToolTip {
            get {
                return ResourceManager.GetString("SelectorProductTaskToolTip", resourceCulture);
            }
        }
    }
}
