//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.Account.Registration", typeof(Registration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ridigitare la password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragione Sociale.
        /// </summary>
        internal static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di telefono.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominativo referente.
        /// </summary>
        internal static string Refeere {
            get {
                return ResourceManager.GetString("Refeere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire indirizzo aziendale.
        /// </summary>
        internal static string RequiredFieldBase {
            get {
                return ResourceManager.GetString("RequiredFieldBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire una email valida.
        /// </summary>
        internal static string RequiredFieldEmail {
            get {
                return ResourceManager.GetString("RequiredFieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire la Ragione Sociale.
        /// </summary>
        internal static string RequiredFieldOrganizationName {
            get {
                return ResourceManager.GetString("RequiredFieldOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire numero aziendale.
        /// </summary>
        internal static string RequiredFieldPhone {
            get {
                return ResourceManager.GetString("RequiredFieldPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire nominativo di un referente.
        /// </summary>
        internal static string RequiredFieldRefeere {
            get {
                return ResourceManager.GetString("RequiredFieldRefeere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inderire il codice fiscale.
        /// </summary>
        internal static string RequiredFieldTaxCode {
            get {
                return ResourceManager.GetString("RequiredFieldTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire un nome utente.
        /// </summary>
        internal static string RequiredFieldUserName {
            get {
                return ResourceManager.GetString("RequiredFieldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire la Partita Iva.
        /// </summary>
        internal static string RequiredFieldVatNumber {
            get {
                return ResourceManager.GetString("RequiredFieldVatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire una password.
        /// </summary>
        internal static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Fiscale.
        /// </summary>
        internal static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Utente.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le due password non combaciano.
        /// </summary>
        internal static string ValidationConfirmPassword {
            get {
                return ResourceManager.GetString("ValidationConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire una email valida.
        /// </summary>
        internal static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password deve contenere almeno 6 caratteri alfanumerici.
        /// </summary>
        internal static string ValidationPassword {
            get {
                return ResourceManager.GetString("ValidationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partita Iva.
        /// </summary>
        internal static string VatNumber {
            get {
                return ResourceManager.GetString("VatNumber", resourceCulture);
            }
        }
    }
}
