//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.Account.Registration", typeof(Registration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ridigitare la password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragione Sociale.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione.
        /// </summary>
        public static string PendingOk1 {
            get {
                return ResourceManager.GetString("PendingOk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avvenuta con successo.
        /// </summary>
        public static string PendingOk2 {
            get {
                return ResourceManager.GetString("PendingOk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di telefono.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gentile Cliente,.
        /// </summary>
        public static string RecoveryBody1 {
            get {
                return ResourceManager.GetString("RecoveryBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to di seguito le credenziali di accesso a PapiroStar da Lei richieste..
        /// </summary>
        public static string RecoveryBody2 {
            get {
                return ResourceManager.GetString("RecoveryBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PapiroStar - Gestionale Cloud per la Stampa.
        /// </summary>
        public static string RecoveryBodyF1 {
            get {
                return ResourceManager.GetString("RecoveryBodyF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PapiroStar credenziali di accesso.
        /// </summary>
        public static string RecoveryTitle {
            get {
                return ResourceManager.GetString("RecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominativo referente.
        /// </summary>
        public static string Refeere {
            get {
                return ResourceManager.GetString("Refeere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grazie per esserti iscritto su PapiroStar!.
        /// </summary>
        public static string RegistrationBody1 {
            get {
                return ResourceManager.GetString("RegistrationBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di seguito i tuoi codici di accesso personali:.
        /// </summary>
        public static string RegistrationBody2 {
            get {
                return ResourceManager.GetString("RegistrationBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prima di procedere con il login è però indispensabile che venga confermata l&apos;iscrizione..
        /// </summary>
        public static string RegistrationBody3 {
            get {
                return ResourceManager.GetString("RegistrationBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicca sul link di seguito:.
        /// </summary>
        public static string RegistrationBody4 {
            get {
                return ResourceManager.GetString("RegistrationBody4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PapiroStar - Gestionale Cloud per la Stampa.
        /// </summary>
        public static string RegistrationBodyF1 {
            get {
                return ResourceManager.GetString("RegistrationBodyF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto su PapiroStar.
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire indirizzo aziendale.
        /// </summary>
        public static string RequiredFieldBase {
            get {
                return ResourceManager.GetString("RequiredFieldBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire una email valida.
        /// </summary>
        public static string RequiredFieldEmail {
            get {
                return ResourceManager.GetString("RequiredFieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire la Ragione Sociale.
        /// </summary>
        public static string RequiredFieldOrganizationName {
            get {
                return ResourceManager.GetString("RequiredFieldOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire numero aziendale.
        /// </summary>
        public static string RequiredFieldPhone {
            get {
                return ResourceManager.GetString("RequiredFieldPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire nominativo di un referente.
        /// </summary>
        public static string RequiredFieldRefeere {
            get {
                return ResourceManager.GetString("RequiredFieldRefeere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inderire il codice fiscale.
        /// </summary>
        public static string RequiredFieldTaxCode {
            get {
                return ResourceManager.GetString("RequiredFieldTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire un nome utente.
        /// </summary>
        public static string RequiredFieldUserName {
            get {
                return ResourceManager.GetString("RequiredFieldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire la Partita Iva.
        /// </summary>
        public static string RequiredFieldVatNumber {
            get {
                return ResourceManager.GetString("RequiredFieldVatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire una password.
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Fiscale.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Utente.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il nome utente contiene spazi o caratteri non validi.
        /// </summary>
        public static string UserNameFormatValidation {
            get {
                return ResourceManager.GetString("UserNameFormatValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9]*$.
        /// </summary>
        public static string UserNameRegex {
            get {
                return ResourceManager.GetString("UserNameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le due password non combaciano.
        /// </summary>
        public static string ValidationConfirmPassword {
            get {
                return ResourceManager.GetString("ValidationConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire una email valida.
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password deve contenere almeno 6 caratteri alfanumerici.
        /// </summary>
        public static string ValidationPassword {
            get {
                return ResourceManager.GetString("ValidationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partita Iva.
        /// </summary>
        public static string VatNumber {
            get {
                return ResourceManager.GetString("VatNumber", resourceCulture);
            }
        }
    }
}
