//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Product
    {
        public Product()
        {
            this.ProductParts = new HashSet<ProductPart>();
            this.ProductTasks = new HashSet<ProductTask>();
            this.documentproducts = new HashSet<DocumentProduct>();
        }
    
        public System.DateTime TimeStampTable { get; set; }
        public string CodProduct { get; set; }
        public string ProductName { get; set; }
        public string CodMenuProduct { get; set; }
    
        public virtual ICollection<ProductPart> ProductParts { get; set; }
        public virtual ICollection<ProductTask> ProductTasks { get; set; }
        public virtual ICollection<DocumentProduct> documentproducts { get; set; }
    }
}
