//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResProduct {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResProduct() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.Products.ResProduct", typeof(ResProduct).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo del Prodotto.
        /// </summary>
        public static string CodMenuProduct {
            get {
                return ResourceManager.GetString("CodMenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altri formati.
        /// </summary>
        public static string CodMenuProductAltriFormati {
            get {
                return ResourceManager.GetString("CodMenuProductAltriFormati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biglietti da visita.
        /// </summary>
        public static string CodMenuProductBigliettiVisita {
            get {
                return ResourceManager.GetString("CodMenuProductBigliettiVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brossura Cucita Filo Refe.
        /// </summary>
        public static string CodMenuProductBrossuraCucitaFilo {
            get {
                return ResourceManager.GetString("CodMenuProductBrossuraCucitaFilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brossura Fresata.
        /// </summary>
        public static string CodMenuProductBrossuraFresata {
            get {
                return ResourceManager.GetString("CodMenuProductBrossuraFresata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buste.
        /// </summary>
        public static string CodMenuProductBuste {
            get {
                return ResourceManager.GetString("CodMenuProductBuste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta intestata.
        /// </summary>
        public static string CodMenuProductCartaIntestata {
            get {
                return ResourceManager.GetString("CodMenuProductCartaIntestata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoline e Inviti.
        /// </summary>
        public static string CodMenuProductCartolineInviti {
            get {
                return ResourceManager.GetString("CodMenuProductCartolineInviti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoline postali.
        /// </summary>
        public static string CodMenuProductCartolinePostali {
            get {
                return ResourceManager.GetString("CodMenuProductCartolinePostali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etichette in piano.
        /// </summary>
        public static string CodMenuProductEtichetteCartellini {
            get {
                return ResourceManager.GetString("CodMenuProductEtichetteCartellini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etichette sagomate in piano.
        /// </summary>
        public static string CodMenuProductEtichetteCartelliniSago {
            get {
                return ResourceManager.GetString("CodMenuProductEtichetteCartelliniSago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etichette quadrate in bobina.
        /// </summary>
        public static string CodMenuProductEtichetteRotolo {
            get {
                return ResourceManager.GetString("CodMenuProductEtichetteRotolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etichette e controetichette.
        /// </summary>
        public static string CodMenuProductEtichetteRotoloDouble {
            get {
                return ResourceManager.GetString("CodMenuProductEtichetteRotoloDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etichette sagomate in bobina.
        /// </summary>
        public static string CodMenuProductEtichetteSagRotolo {
            get {
                return ResourceManager.GetString("CodMenuProductEtichetteSagRotolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fasce Gommate in bobina.
        /// </summary>
        public static string CodMenuProductFasceGommateRotolo {
            get {
                return ResourceManager.GetString("CodMenuProductFasceGommateRotolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etichette film.
        /// </summary>
        public static string CodMenuProductFasceGommateRotolo2 {
            get {
                return ResourceManager.GetString("CodMenuProductFasceGommateRotolo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fogli macchina.
        /// </summary>
        public static string CodMenuProductFogliMacchina {
            get {
                return ResourceManager.GetString("CodMenuProductFogliMacchina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clichè fotopolimero.
        /// </summary>
        public static string CodMenuProductFotopolimero {
            get {
                return ResourceManager.GetString("CodMenuProductFotopolimero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoquadri.
        /// </summary>
        public static string CodMenuProductFotoquadri {
            get {
                return ResourceManager.GetString("CodMenuProductFotoquadri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clichè inciso.
        /// </summary>
        public static string CodMenuProductInciso {
            get {
                return ResourceManager.GetString("CodMenuProductInciso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locandine.
        /// </summary>
        public static string CodMenuProductLocandine {
            get {
                return ResourceManager.GetString("CodMenuProductLocandine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifesti per affissione.
        /// </summary>
        public static string CodMenuProductManifesti {
            get {
                return ResourceManager.GetString("CodMenuProductManifesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieghevoli.
        /// </summary>
        public static string CodMenuProductPieghevoli {
            get {
                return ResourceManager.GetString("CodMenuProductPieghevoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster altissima qualità.
        /// </summary>
        public static string CodMenuProductPoster {
            get {
                return ResourceManager.GetString("CodMenuProductPoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto Metallico.
        /// </summary>
        public static string CodMenuProductPuntoMetallico {
            get {
                return ResourceManager.GetString("CodMenuProductPuntoMetallico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVC adesivo.
        /// </summary>
        public static string CodMenuProductPVC {
            get {
                return ResourceManager.GetString("CodMenuProductPVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riviste Per Postalizzazione.
        /// </summary>
        public static string CodMenuProductRivistePostalizzazione {
            get {
                return ResourceManager.GetString("CodMenuProductRivistePostalizzazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schede Non Rilegate.
        /// </summary>
        public static string CodMenuProductSchedeNonRilegate {
            get {
                return ResourceManager.GetString("CodMenuProductSchedeNonRilegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirale Metallica.
        /// </summary>
        public static string CodMenuProductSpiraleMetallica {
            get {
                return ResourceManager.GetString("CodMenuProductSpiraleMetallica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Striscioni, Microforato.
        /// </summary>
        public static string CodMenuProductStriscioni {
            get {
                return ResourceManager.GetString("CodMenuProductStriscioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporti rigidi.
        /// </summary>
        public static string CodMenuProductSuppRigidi {
            get {
                return ResourceManager.GetString("CodMenuProductSuppRigidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipologia del prodotto .
        /// </summary>
        public static string CodMenuProductToolTip {
            get {
                return ResourceManager.GetString("CodMenuProductToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volantini e Flyer.
        /// </summary>
        public static string CodMenuProductVolantini {
            get {
                return ResourceManager.GetString("CodMenuProductVolantini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generico.
        /// </summary>
        public static string CodMenuProductVuoto {
            get {
                return ResourceManager.GetString("CodMenuProductVuoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice del prodotto.
        /// </summary>
        public static string CodProduct {
            get {
                return ResourceManager.GetString("CodProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice del prodotto.
        /// </summary>
        public static string CodProductToolTip {
            get {
                return ResourceManager.GetString("CodProductToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formato chiuso cm.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.to cm.
        /// </summary>
        public static string FormatA {
            get {
                return ResourceManager.GetString("FormatA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.to contro etichetta cm.
        /// </summary>
        public static string FormatB {
            get {
                return ResourceManager.GetString("FormatB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formato cm.
        /// </summary>
        public static string FormatOnly {
            get {
                return ResourceManager.GetString("FormatOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formato aperto cm.
        /// </summary>
        public static string FormatOpened {
            get {
                return ResourceManager.GetString("FormatOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generatore.
        /// </summary>
        public static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generatore della descrizione.
        /// </summary>
        public static string GeneratorToolTip {
            get {
                return ResourceManager.GetString("GeneratorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome prodotto.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome descrittivo del prodotto.
        /// </summary>
        public static string ProductNameToolTip {
            get {
                return ResourceManager.GetString("ProductNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
    }
}
