//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResProductPartTask {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResProductPartTask() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.Products.ResProductPartTask", typeof(ResProductPartTask).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoppiati su un lato solo.
        /// </summary>
        public static string CodACCOPPIATURA_1LATO {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA_1LATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoppiati su due lati.
        /// </summary>
        public static string CodACCOPPIATURA_2LATI {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA_2LATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoppiati su tre lati.
        /// </summary>
        public static string CodACCOPPIATURA_3LATI {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA_3LATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodACCOPPIATURA_NO {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodCodTAGLIO_DOPPIO {
            get {
                return ResourceManager.GetString("CodCodTAGLIO_DOPPIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodFORO_NO {
            get {
                return ResourceManager.GetString("CodFORO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Foro.
        /// </summary>
        public static string CodFORO_SI {
            get {
                return ResourceManager.GetString("CodFORO_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fustellatura in linea.
        /// </summary>
        public static string CodFUSTELLATURA_NO {
            get {
                return ResourceManager.GetString("CodFUSTELLATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fustellatura.
        /// </summary>
        public static string CodFUSTELLATURA_NO_STACCO {
            get {
                return ResourceManager.GetString("CodFUSTELLATURA_NO_STACCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fustellatura con stacco.
        /// </summary>
        public static string CodFUSTELLATURA_STACCO {
            get {
                return ResourceManager.GetString("CodFUSTELLATURA_STACCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercalati.
        /// </summary>
        public static string CodINTERCALATURA_2COPIE {
            get {
                return ResourceManager.GetString("CodINTERCALATURA_2COPIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercalati.
        /// </summary>
        public static string CodINTERCALATURA_3COPIE {
            get {
                return ResourceManager.GetString("CodINTERCALATURA_3COPIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercalati.
        /// </summary>
        public static string CodINTERCALATURA_4COPIE {
            get {
                return ResourceManager.GetString("CodINTERCALATURA_4COPIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodINTERCALATURA_NO {
            get {
                return ResourceManager.GetString("CodINTERCALATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piegati  a 2 ante.
        /// </summary>
        public static string CodPIEGA_2ANTE {
            get {
                return ResourceManager.GetString("CodPIEGA_2ANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piegati  a 3 ante.
        /// </summary>
        public static string CodPIEGA_3ANTE {
            get {
                return ResourceManager.GetString("CodPIEGA_3ANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodPIEGA_NO {
            get {
                return ResourceManager.GetString("CodPIEGA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastificatura.
        /// </summary>
        public static string CodPLASTIFICATURA {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastificati con film lucido su 1 Lato.
        /// </summary>
        public static string CodPLASTIFICATURA_LUCIDA1 {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_LUCIDA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastificati con film lucido su 2 Lati.
        /// </summary>
        public static string CodPLASTIFICATURA_LUCIDA2 {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_LUCIDA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodPLASTIFICATURA_NO {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastificati con film lucido su 1 Lato.
        /// </summary>
        public static string CodPLASTIFICATURA_OPACA1 {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_OPACA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastificati con film lucido su 2 Lati.
        /// </summary>
        public static string CodPLASTIFICATURA_OPACA2 {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_OPACA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice .
        /// </summary>
        public static string CodProductCaption {
            get {
                return ResourceManager.GetString("CodProductCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice parte del prodotto.
        /// </summary>
        public static string CodProductPart {
            get {
                return ResourceManager.GetString("CodProductPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice del compito della parte del prodotto.
        /// </summary>
        public static string CodProductPartTask {
            get {
                return ResourceManager.GetString("CodProductPartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice del compito della parte del prodotto.
        /// </summary>
        public static string CodProductPartTaskToolTip {
            get {
                return ResourceManager.GetString("CodProductPartTaskToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice parte del prodotto.
        /// </summary>
        public static string CodProductPartToolTip {
            get {
                return ResourceManager.GetString("CodProductPartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string CodProductTask {
            get {
                return ResourceManager.GetString("CodProductTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string CodProductTaskToolTip {
            get {
                return ResourceManager.GetString("CodProductTaskToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegati con brossura filorefe.
        /// </summary>
        public static string CodRILEGATURA_BROSSURA_FILOREFE {
            get {
                return ResourceManager.GetString("CodRILEGATURA_BROSSURA_FILOREFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegati con brossura gregata fresata.
        /// </summary>
        public static string CodRILEGATURA_BROSSURA_GREGATA_FRESATA {
            get {
                return ResourceManager.GetString("CodRILEGATURA_BROSSURA_GREGATA_FRESATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodRILEGATURA_BROSSURA_NO {
            get {
                return ResourceManager.GetString("CodRILEGATURA_BROSSURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegati a 2 punti metallici.
        /// </summary>
        public static string CodRILEGATURA_PM_2PUNTI {
            get {
                return ResourceManager.GetString("CodRILEGATURA_PM_2PUNTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodRILEGATURA_PM_NO {
            get {
                return ResourceManager.GetString("CodRILEGATURA_PM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirale.
        /// </summary>
        public static string CodRILEGATURA_SPIRALE {
            get {
                return ResourceManager.GetString("CodRILEGATURA_SPIRALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodRILEGATURA_SPIRALE_NO {
            get {
                return ResourceManager.GetString("CodRILEGATURA_SPIRALE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirale.
        /// </summary>
        public static string CodRILEGATURA_SPIRALE_SI {
            get {
                return ResourceManager.GetString("CodRILEGATURA_SPIRALE_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodRILIEVO_A_SECCO_NO {
            get {
                return ResourceManager.GetString("CodRILIEVO_A_SECCO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilevo a secco.
        /// </summary>
        public static string CodRILIEVO_A_SECCO_SI {
            get {
                return ResourceManager.GetString("CodRILIEVO_A_SECCO_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro in bianco e nero.
        /// </summary>
        public static string CodSTAMPA_FR_BN {
            get {
                return ResourceManager.GetString("CodSTAMPA_FR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro a colori.
        /// </summary>
        public static string CodSTAMPA_FR_COL {
            get {
                return ResourceManager.GetString("CodSTAMPA_FR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte in bianco e nero.
        /// </summary>
        public static string CodSTAMPA_FRONTE_BN {
            get {
                return ResourceManager.GetString("CodSTAMPA_FRONTE_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte a colori.
        /// </summary>
        public static string CodSTAMPA_FRONTE_COL {
            get {
                return ResourceManager.GetString("CodSTAMPA_FRONTE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPA_NO {
            get {
                return ResourceManager.GetString("CodSTAMPA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro in bianco e nero.
        /// </summary>
        public static string CodSTAMPADIGITALE_FR_BN {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_FR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro a colori.
        /// </summary>
        public static string CodSTAMPADIGITALE_FR_COL {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_FR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte in bianco e nero.
        /// </summary>
        public static string CodSTAMPADIGITALE_FRONTE_BN {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_FRONTE_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte a colori.
        /// </summary>
        public static string CodSTAMPADIGITALE_FRONTE_COL {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_FRONTE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPADIGITALE_NO {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa a 1 colore.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_1 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa a 2 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_2 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa a 3 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_3 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa a 4 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_4 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa a 5 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_5 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa a 6 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_6 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV alta qualità.
        /// </summary>
        public static string CodSTAMPAMORBIDO_ALTA {
            get {
                return ResourceManager.GetString("CodSTAMPAMORBIDO_ALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV bassa qualità.
        /// </summary>
        public static string CodSTAMPAMORBIDO_BASSA {
            get {
                return ResourceManager.GetString("CodSTAMPAMORBIDO_BASSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV media qualità.
        /// </summary>
        public static string CodSTAMPAMORBIDO_MEDIA {
            get {
                return ResourceManager.GetString("CodSTAMPAMORBIDO_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPAMORBIDO_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAMORBIDO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro in bianco e nero.
        /// </summary>
        public static string CodSTAMPAOFF_FR_BN {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_FR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro a colori.
        /// </summary>
        public static string CodSTAMPAOFF_FR_COL {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_FR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte in bianco e nero.
        /// </summary>
        public static string CodSTAMPAOFF_FRONTE_BN {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_FRONTE_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte a colori.
        /// </summary>
        public static string CodSTAMPAOFF_FRONTE_COL {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_FRONTE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPAOFF_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPAOFFaROTOLO_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFaROTOLO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro in bianco e nero.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_FR_BN {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_FR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro a colori.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_FR_COL {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_FR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte in bianco e nero.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_FRONTE_BN {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_FRONTE_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte a colori.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_FRONTE_COL {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_FRONTE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV alta qualità.
        /// </summary>
        public static string CodSTAMPARIGIDO_ALTA {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_ALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV alta qualità Day/Night.
        /// </summary>
        public static string CodSTAMPARIGIDO_ALTADN {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_ALTADN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV alta qualità e bianco.
        /// </summary>
        public static string CodSTAMPARIGIDO_ALTAW {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_ALTAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV bassa qualità.
        /// </summary>
        public static string CodSTAMPARIGIDO_BASSA {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_BASSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV bassa qualità Day/Night.
        /// </summary>
        public static string CodSTAMPARIGIDO_BASSADN {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_BASSADN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV bassa qualità e bianco.
        /// </summary>
        public static string CodSTAMPARIGIDO_BASSAW {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_BASSAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV media qualità.
        /// </summary>
        public static string CodSTAMPARIGIDO_MEDIA {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV media qualità Day/Night.
        /// </summary>
        public static string CodSTAMPARIGIDO_MEDIADN {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_MEDIADN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV media qualità e bianco.
        /// </summary>
        public static string CodSTAMPARIGIDO_MEDIAW {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_MEDIAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPARIGIDO_NO {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglio al vivo.
        /// </summary>
        public static string CodTAGLIO_AL_VIVO {
            get {
                return ResourceManager.GetString("CodTAGLIO_AL_VIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodTAGLIO_NO {
            get {
                return ResourceManager.GetString("CodTAGLIO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verniciatura Lucida 1 Lato.
        /// </summary>
        public static string CodVERNICIATURA_LUCIDA1 {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_LUCIDA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verniciatura  2 Lati.
        /// </summary>
        public static string CodVERNICIATURA_LUCIDA2 {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_LUCIDA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodVERNICIATURA_NO {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verniciatura Opaca 1 Lato.
        /// </summary>
        public static string CodVERNICIATURA_OPACA1 {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_OPACA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verniciatura Opaca 2 Lati.
        /// </summary>
        public static string CodVERNICIATURA_OPACA2 {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_OPACA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavorazione nascosta.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavorazione nascosta.
        /// </summary>
        public static string HiddenToolTip {
            get {
                return ResourceManager.GetString("HiddenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string IndexOf {
            get {
                return ResourceManager.GetString("IndexOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string IndexOfToolTip {
            get {
                return ResourceManager.GetString("IndexOfToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte del prodotto.
        /// </summary>
        public static string ProductPart {
            get {
                return ResourceManager.GetString("ProductPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte del prodotto.
        /// </summary>
        public static string ProductPartToolTip {
            get {
                return ResourceManager.GetString("ProductPartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string ProductTask {
            get {
                return ResourceManager.GetString("ProductTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        public static string ProductTaskToolTip {
            get {
                return ResourceManager.GetString("ProductTaskToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
    }
}
