//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResProductPart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResProductPart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.Products.ResProductPart", typeof(ResProductPart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato acquisto.
        /// </summary>
        public static string BuyingFormat {
            get {
                return ResourceManager.GetString("BuyingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato acquisto del materiale.
        /// </summary>
        public static string BuyingFormatToolTip {
            get {
                return ResourceManager.GetString("BuyingFormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice del prodotto.
        /// </summary>
        public static string CodProduct {
            get {
                return ResourceManager.GetString("CodProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice della parte del prodotto.
        /// </summary>
        public static string CodProductPar {
            get {
                return ResourceManager.GetString("CodProductPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice della parte del prodotto.
        /// </summary>
        public static string CodProductPartToolTiCodProductPartToolTi {
            get {
                return ResourceManager.GetString("CodProductPartToolTiCodProductPartToolTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice del prodotto.
        /// </summary>
        public static string CodProductToolTip {
            get {
                return ResourceManager.GetString("CodProductToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaziatura cm.
        /// </summary>
        public static string DCut {
            get {
                return ResourceManager.GetString("DCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.spazio cm.
        /// </summary>
        public static string DCut1 {
            get {
                return ResourceManager.GetString("DCut1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo spazio viene lasciato tra una posa e un&apos;altra, lungo il primo lato.
        /// </summary>
        public static string DCut1ToolTip {
            get {
                return ResourceManager.GetString("DCut1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.spazio cm.
        /// </summary>
        public static string DCut2 {
            get {
                return ResourceManager.GetString("DCut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo spazio viene lasciato tra una posa e un&apos;altra, lungo il secondo lato.
        /// </summary>
        public static string DCut2ToolTip {
            get {
                return ResourceManager.GetString("DCut2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo spazio viene lasciato tra una posa e un&apos;altra.
        /// </summary>
        public static string DCutToolTip {
            get {
                return ResourceManager.GetString("DCutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.to chiuso lavoro.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.to etichetta.
        /// </summary>
        public static string FormatLabel {
            get {
                return ResourceManager.GetString("FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.to dell&apos;etichetta da stampare.
        /// </summary>
        public static string FormatLabelToolTip {
            get {
                return ResourceManager.GetString("FormatLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato personalizzato.
        /// </summary>
        public static string FormatPersonalized {
            get {
                return ResourceManager.GetString("FormatPersonalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato personalizzato.
        /// </summary>
        public static string FormatPersonalizedToolTip {
            get {
                return ResourceManager.GetString("FormatPersonalizedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato chiuso del lavoro finito.
        /// </summary>
        public static string FormatToolTip {
            get {
                return ResourceManager.GetString("FormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\d{1,4})((\,\d{0,5}){0,1})[xX](\d{1,4})((\,\d{0,5}){0,1})?$.
        /// </summary>
        public static string FormatValidation {
            get {
                return ResourceManager.GetString("FormatValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formato non valido.
        /// </summary>
        public static string FormatValidationError {
            get {
                return ResourceManager.GetString("FormatValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaziatura tra Soggeti.
        /// </summary>
        public static string IsDCut {
            get {
                return ResourceManager.GetString("IsDCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostare quando le pose sono spaziate una con l&apos;altra.
        /// </summary>
        public static string IsDCutToolTip {
            get {
                return ResourceManager.GetString("IsDCutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato di stampa.
        /// </summary>
        public static string PrintingFormat {
            get {
                return ResourceManager.GetString("PrintingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato di stampa su cui è posto il lavoro.
        /// </summary>
        public static string PrintingFormatToolTip {
            get {
                return ResourceManager.GetString("PrintingFormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di Stampa.
        /// </summary>
        public static string PrintingType {
            get {
                return ResourceManager.GetString("PrintingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di Stampa.
        /// </summary>
        public static string PrintingTypeToolTip {
            get {
                return ResourceManager.GetString("PrintingTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotto.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interni.
        /// </summary>
        public static string ProductPartBookSheet {
            get {
                return ResourceManager.GetString("ProductPartBookSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copertina.
        /// </summary>
        public static string ProductPartCoverSheet {
            get {
                return ResourceManager.GetString("ProductPartCoverSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome della parte del prodotto.
        /// </summary>
        public static string ProductPartName {
            get {
                return ResourceManager.GetString("ProductPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome della parte del prodotto.
        /// </summary>
        public static string ProductPartNameToolTip {
            get {
                return ResourceManager.GetString("ProductPartNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compito della parte del prodotto.
        /// </summary>
        public static string ProductPartTasks {
            get {
                return ResourceManager.GetString("ProductPartTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compito della parte del prodotto.
        /// </summary>
        public static string ProductPartTasksToolTip {
            get {
                return ResourceManager.GetString("ProductPartTasksToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotto.
        /// </summary>
        public static string ProductToolTip {
            get {
                return ResourceManager.GetString("ProductToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Servizi.
        /// </summary>
        public static string ServicesNumber {
            get {
                return ResourceManager.GetString("ServicesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Servizi.
        /// </summary>
        public static string ServicesNumberToolTip {
            get {
                return ResourceManager.GetString("ServicesNumberToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verso.
        /// </summary>
        public static string SideOnSIde {
            get {
                return ResourceManager.GetString("SideOnSIde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verso delle pose sul materiale.
        /// </summary>
        public static string SideOnSideToolTip {
            get {
                return ResourceManager.GetString("SideOnSideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Soggetti.
        /// </summary>
        public static string SubjectNumber {
            get {
                return ResourceManager.GetString("SubjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il numero di soggetti differti in stampa con lo stesso formato e caratteristiche .
        /// </summary>
        public static string SubjectNumberToolTip {
            get {
                return ResourceManager.GetString("SubjectNumberToolTip", resourceCulture);
            }
        }
    }
}
