//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.Articles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResArticle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResArticle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.Articles.ResArticle", typeof(ResArticle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ArticleName {
            get {
                return ResourceManager.GetString("ArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome descrittivo dell&apos;articolo.
        /// </summary>
        public static string ArticleNameToolTip {
            get {
                return ResourceManager.GetString("ArticleNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Articolo.
        /// </summary>
        public static string CodArticle {
            get {
                return ResourceManager.GetString("CodArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il codice articolo è assegnato automaticamente dal sistema.
        /// </summary>
        public static string CodArticleToolTip {
            get {
                return ResourceManager.GetString("CodArticleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice fustella.
        /// </summary>
        public static string CodDie {
            get {
                return ResourceManager.GetString("CodDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interspazio verticale.
        /// </summary>
        public static string DCut1 {
            get {
                return ResourceManager.GetString("DCut1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.Spazio Banda.
        /// </summary>
        public static string DCut1Flexo {
            get {
                return ResourceManager.GetString("DCut1Flexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interspazio orizzontale.
        /// </summary>
        public static string DCut2 {
            get {
                return ResourceManager.GetString("DCut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.Spazio Passo.
        /// </summary>
        public static string DCut2Flexo {
            get {
                return ResourceManager.GetString("DCut2Flexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione fustella.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fomato (cm x cm).
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\d{1,4})((\,\d{0,5}){0,1})[xX](\d{1,4})((\,\d{0,5}){0,1})?$.
        /// </summary>
        public static string FormatValidation {
            get {
                return ResourceManager.GetString("FormatValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formato carta non valido (es. valido: 70x100).
        /// </summary>
        public static string FormatValidationError {
            get {
                return ResourceManager.GetString("FormatValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resa lato 1.
        /// </summary>
        public static string MaxGain1 {
            get {
                return ResourceManager.GetString("MaxGain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resa in banda.
        /// </summary>
        public static string MaxGain1Flexo {
            get {
                return ResourceManager.GetString("MaxGain1Flexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resa lato 2.
        /// </summary>
        public static string MaxGain2 {
            get {
                return ResourceManager.GetString("MaxGain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resa in passo.
        /// </summary>
        public static string MaxGain2Flexo {
            get {
                return ResourceManager.GetString("MaxGain2Flexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato di stampa.
        /// </summary>
        public static string PrintingFormat {
            get {
                return ResourceManager.GetString("PrintingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unità di misura.
        /// </summary>
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banda.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilindro Z.
        /// </summary>
        public static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
