//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models.Resources.Articles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPrintable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPrintable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Models.Resources.Articles.ResPrintable", typeof(ResPrintable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di adesivo.
        /// </summary>
        public static string Adhesive {
            get {
                return ResourceManager.GetString("Adhesive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il tipo di adesivo.
        /// </summary>
        public static string AdhesiveToolTip {
            get {
                return ResourceManager.GetString("AdhesiveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colore.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mano.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome materiale.
        /// </summary>
        public static string NameOfMaterial {
            get {
                return ResourceManager.GetString("NameOfMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es. &apos;Hello&apos;, &apos;Garda&apos;, etc... per le patinate; &apos;3mm&apos;, &apos;5mm&apos; per il Forex, etc....
        /// </summary>
        public static string NameOfMaterialToolTip {
            get {
                return ResourceManager.GetString("NameOfMaterialToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no b/v.
        /// </summary>
        public static string NoBv {
            get {
                return ResourceManager.GetString("NoBv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non usare in preventivo.
        /// </summary>
        public static string NoUseInEstimateCalculation {
            get {
                return ResourceManager.GetString("NoUseInEstimateCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usando questa opzione si esclude questo tipo di materiale (solitamente per il formato) dal calcolo ottimizzato del preventivo.
        /// </summary>
        public static string NoUseInEstimateCalculationCaption {
            get {
                return ResourceManager.GetString("NoUseInEstimateCalculationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spessore.
        /// </summary>
        public static string Thikness {
            get {
                return ResourceManager.GetString("Thikness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di materiale.
        /// </summary>
        public static string TypeOfMaterial {
            get {
                return ResourceManager.GetString("TypeOfMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es. &apos;Patinata Lucida, &apos;Patinata Opaca&apos;, &apos;UsoMano&apos;, etc... per i foglio e le bobine; &apos;Forex&apos;, &apos;Polyonda&apos;, etc... per i rigidi.
        /// </summary>
        public static string TypeOfMaterialToolTip {
            get {
                return ResourceManager.GetString("TypeOfMaterialToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gr/mq.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
