//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BindingCostPerRunStep : Step
    {
        public Nullable<double> CostPerUnit4 { get; set; }
        public Nullable<double> StartingCost4 { get; set; }
        public Nullable<double> CostPerUnit6 { get; set; }
        public Nullable<double> StartingCost6 { get; set; }
        public Nullable<double> CostPerUnit8 { get; set; }
        public Nullable<double> StartingCost8 { get; set; }
        public Nullable<double> CostPerUnit12 { get; set; }
        public Nullable<double> StartingCost12 { get; set; }
        public Nullable<double> CostPerUnit16 { get; set; }
        public Nullable<double> StartingCost16 { get; set; }
        public Nullable<double> CostPerUnit24 { get; set; }
        public Nullable<double> StartingCost24 { get; set; }
        public Nullable<double> CostPerUnit32 { get; set; }
        public Nullable<double> StartingCost32 { get; set; }
        public Nullable<double> BindingCost { get; set; }
    }
}
