//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BindingEstimatedOnTime : TaskEstimatedOn
    {
        public Nullable<long> AvarageRunPerHour4 { get; set; }
        public Nullable<System.TimeSpan> StartingTime4 { get; set; }
        public Nullable<long> AvarageRunPerHour6 { get; set; }
        public Nullable<System.TimeSpan> StartingTime6 { get; set; }
        public Nullable<long> AvarageRunPerHour8 { get; set; }
        public Nullable<System.TimeSpan> StartingTime8 { get; set; }
        public Nullable<long> AvarageRunPerHour12 { get; set; }
        public Nullable<System.TimeSpan> StartingTime12 { get; set; }
        public Nullable<long> AvarageRunPerHour16 { get; set; }
        public Nullable<System.TimeSpan> StartingTime16 { get; set; }
        public Nullable<long> AvarageRunPerHour24 { get; set; }
        public Nullable<System.TimeSpan> StartingTime24 { get; set; }
        public Nullable<long> AvarageRunPerHour32 { get; set; }
        public Nullable<System.TimeSpan> StartingTime32 { get; set; }
        public Nullable<long> AvarageRunPerHourBinding { get; set; }
        public Nullable<System.TimeSpan> StartingTimeBinding { get; set; }
        public string CostPerHourRunning { get; set; }
        public string CostPerHourStarting { get; set; }
    }
}
