//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class BindingEstimatedOnRun : TaskEstimatedOn
    {
    	
    	[DataMember] 		
        public string CostPerUnit4 { get; set; }
    	
    	[DataMember] 		
        public string StartingCost4 { get; set; }
    	
    	[DataMember] 		
        public string CostPerUnit6 { get; set; }
    	
    	[DataMember] 		
        public string StartingCost6 { get; set; }
    	
    	[DataMember] 		
        public string CostPerUnit8 { get; set; }
    	
    	[DataMember] 		
        public string StartingCost8 { get; set; }
    	
    	[DataMember] 		
        public string CostPerUnit12 { get; set; }
    	
    	[DataMember] 		
        public string StartingCost12 { get; set; }
    	
    	[DataMember] 		
        public string CostPerUnit16 { get; set; }
    	
    	[DataMember] 		
        public string StartingCost16 { get; set; }
    	
    	[DataMember] 		
        public string CostPerUnit24 { get; set; }
    	
    	[DataMember] 		
        public string StartingCost24 { get; set; }
    	
    	[DataMember] 		
        public string CostPerUnit32 { get; set; }
    	
    	[DataMember] 		
        public string StartingCost32 { get; set; }
    	
    	[DataMember] 		
        public string BindingCost { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseDifferentCostPerUnit { get; set; }
    	
    	[DataMember] 		
        public string BindingStartingCost { get; set; }
    }
}
