//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class CostDetail
    {
        public CostDetail()
        {
            this.Computes = new HashSet<CostDetail>();
            this.GainPrintingOnBuyings = new HashSet<ProductPartPrintingGain>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodCostDetail { get; set; }
    	
    	[DataMember] 		
        public string CodTaskExecutorSelected { get; set; }
    	
    	[DataMember] 		
        public string CodCost { get; set; }
    	
    	[DataMember] 		
        public string CodProductPart { get; set; }
    	
    	[DataMember] 		
        public string CodComputedBy { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> Starts { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> GainForRun { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> GainForRunForPrintableArticle { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> GainForMqRun { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> GainForMqRunForPrintableArticle { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> TypeOfQuantity { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> GainForWeigthRun { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> GainForWeigthRunForPrintableArticle { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> Error { get; set; }
    	
    	[DataMember] 		
        public string Guid { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> RollChanges { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> Implants { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> CalculatedMq { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> CalculatedMl { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> CalculatedRun { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> CalculatedKg { get; set; }
    	
    	[DataMember] 		
        public Nullable<System.TimeSpan> CalculatedTime { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> Washes { get; set; }
    
    	[DataMember]
        public virtual Cost TaskCost { get; set; }
    	[DataMember]
        public virtual ProductPart ProductPart { get; set; }
    	[DataMember]
        public virtual TaskExecutor TaskexEcutorSelected { get; set; }
    	[DataMember]
        public virtual ICollection<CostDetail> Computes { get; set; }
    	[DataMember]
        public virtual CostDetail ComputedBy { get; set; }
    	[DataMember]
        public virtual ProductPartPrinting ProductPartPrinting { get; set; }
    	[DataMember]
        public virtual ICollection<ProductPartPrintingGain> GainPrintingOnBuyings { get; set; }
    }
}
