//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSupplierBase
    {
        public System.DateTime TimeStampTable { get; set; }
        public string CodCustomerSupplier { get; set; }
        public string CodCustomerSupplierBase { get; set; }
        public string CodTypeOfBase { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public string Referee { get; set; }
        public string Pec { get; set; }
        public string Province { get; set; }
    
        public virtual CustomerSupplier CustomerSupplier { get; set; }
        public virtual TypeOfBase TypeOfBase { get; set; }
    }
}
