//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public abstract partial class CustomerSupplier
    {
        public CustomerSupplier()
        {
            this.CustomerSupplierBases = new HashSet<CustomerSupplierBase>();
            this.articles = new HashSet<Article>();
            this.articles1 = new HashSet<Article>();
            this.documents = new HashSet<Document>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodCustomerSupplier { get; set; }
    	
    	[DataMember] 		
        public string BusinessName { get; set; }
    	
    	[DataMember] 		
        public string VatNumber { get; set; }
    	
    	[DataMember] 		
        public string TaxCode { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> Outdated { get; set; }
    
    	[DataMember]
        public virtual ICollection<CustomerSupplierBase> CustomerSupplierBases { get; set; }
    	[DataMember]
        public virtual ICollection<Article> articles { get; set; }
    	[DataMember]
        public virtual ICollection<Article> articles1 { get; set; }
    	[DataMember]
        public virtual ICollection<Document> documents { get; set; }
    }
}
