//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class DigitalOnRun : TaskEstimatedOnRun
    {
    	
    	[DataMember] 		
        public string StartingCost1BW { get; set; }
    	
    	[DataMember] 		
        public string StartingCost2BW { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseDifferentCostPerUnitBW { get; set; }
    	
    	[DataMember] 		
        public string CostForfaitBW { get; set; }
    	
    	[DataMember] 		
        public string CostForfaitForSheetBW { get; set; }
    }
}
