//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class FlatRoll : Litho
    {
    	
    	[DataMember] 		
        public Nullable<double> Width2 { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> Serigraphy { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> SerigraphyPrintingUnit { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> FoilStamping { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> FoilStampingPrintingUnit { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> DieCutting { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> FlatRollWidth { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> ProofSheetFirstStartSerigraphy { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> ProofSheetFirstStartFoilStamping { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> ProofSheetFirstStartDieCutting { get; set; }
    	
    	[DataMember] 		
        public string CostImplantFoilStamping { get; set; }
    	
    	[DataMember] 		
        public string CostImplantDieCutting { get; set; }
    }
}
