//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public abstract partial class Litho : PrinterMachine
    {
    	
    	[DataMember] 		
        public Nullable<short> PrintingUnit { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> SheetwiseAfterPrintingUnit { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> Sheetwise { get; set; }
    	
    	[DataMember] 		
        public Nullable<System.TimeSpan> WashUpTime { get; set; }
    	
    	[DataMember] 		
        public Nullable<System.TimeSpan> ChangePlateTime { get; set; }
    }
}
