//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class Makeready
    {
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodMakeready { get; set; }
    	
    	[DataMember] 		
        public string CodProductPartPrintingGain { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> ShapeOnSide1 { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> SideOnSide { get; set; }
    	
    	[DataMember] 		
        public Nullable<decimal> CalculatedGain { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> ShapeOnSide2 { get; set; }
    
    	[DataMember]
        public virtual ProductPartPrintingGain ProductPartPrintingGain { get; set; }
    }
}
