//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class MakereadyPrintingBookSheet : Makeready
    {
    	
    	[DataMember] 		
        public string TypeOfPerfecting { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> PrintablePages { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> PrintedPages { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> CodMaxSegn { get; set; }
    }
}
