//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakereadyPrintingBookSheet : Makeready
    {
        public string TypeOfPerfecting { get; set; }
        public Nullable<int> PrintablePages { get; set; }
        public Nullable<int> PrintedPages { get; set; }
        public Nullable<int> CodMaxSegn { get; set; }
    }
}
