//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class MenuProduct
    {
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodMenuProduct { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> Enabled { get; set; }
    	
    	[DataMember] 		
        public string CodCategory { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> Hidden { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> IndexOf { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> IndexOfCategory { get; set; }
    }
}
