//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotterOnMq : TaskEstimatedOnMq
    {
        public string CostInkJetLow { get; set; }
        public string CostInkJetMed { get; set; }
        public string CostInkJetHight { get; set; }
        public string CostUVLow { get; set; }
        public string CostUVMed { get; set; }
        public string CostUVHight { get; set; }
        public string CostWhite { get; set; }
        public string CostCutting { get; set; }
    }
}
