//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Printable : Article
    {
        public string TypeOfMaterial { get; set; }
        public Nullable<long> Weight { get; set; }
        public string Color { get; set; }
        public Nullable<double> Thikness { get; set; }
        public string NameOfMaterial { get; set; }
        public Nullable<bool> NoBv { get; set; }
        public Nullable<double> Hand { get; set; }
        public string SupplierMaker { get; set; }
    }
}
