//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class PrinterMachine : TaskExecutor
    {
        public Nullable<double> InkUsage { get; set; }
        public Nullable<double> InkUsageForfait { get; set; }
    }
}
