//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPart
    {
        public ProductPart()
        {
            this.ProductPartPrintableArticles = new HashSet<ProductPartsPrintableArticle>();
            this.ProductPartTasks = new HashSet<ProductPartTask>();
        }
    
        public System.DateTime TimeStampTable { get; set; }
        public string CodProductPart { get; set; }
        public string CodProduct { get; set; }
        public string ProductPartName { get; set; }
        public Nullable<int> SelectorProductPart { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductPartsPrintableArticle> ProductPartPrintableArticles { get; set; }
        public virtual ICollection<ProductPartTask> ProductPartTasks { get; set; }
    }
}
