//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public abstract partial class ProductPartPrintingGain
    {
        public ProductPartPrintingGain()
        {
            this.Makereadies = new HashSet<Makeready>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodProductPartPrintingGain { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UsePerfecting { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> MaxShape { get; set; }
    	
    	[DataMember] 		
        public string CodProductPartPrintingGainBuying { get; set; }
    	
    	[DataMember] 		
        public string CodProductPartPrinting { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> DCut { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> IsDCut { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> DCut1 { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> DCut2 { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> ForceSideOnSide { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> ForceGain { get; set; }
    
    	[DataMember]
        public virtual ProductPartPrinting ProductPartPrinting___ { get; set; }
    	[DataMember]
        public virtual ICollection<Makeready> Makereadies { get; set; }
    	[DataMember]
        public virtual CostDetail CostDetail { get; set; }
    	[DataMember]
        public virtual ProductPartPrinting ProductPartPrinting { get; set; }
    }
}
