//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPartsPrintableArticle
    {
        public System.DateTime TimeStampTable { get; set; }
        public string CodProductPartPrintableArticle { get; set; }
        public string CodProductPart { get; set; }
        public string ProductPartPrintableArticleName { get; set; }
        public Nullable<int> SelectorProductPartPrintableArticle { get; set; }
    
        public virtual ProductPart ProductPart { get; set; }
    }
}
