//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public abstract partial class Product
    {
        public Product()
        {
            this.ProductParts = new HashSet<ProductPart>();
            this.ProductTasks = new HashSet<ProductTask>();
            this.documentproducts = new HashSet<DocumentProduct>();
            this.ProductGraphLinks = new HashSet<ProductGraphLink>();
            this.WarehouseArticles = new HashSet<Warehouse>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodProduct { get; set; }
    	
    	[DataMember] 		
        public string ProductName { get; set; }
    	
    	[DataMember] 		
        public string CodMenuProduct { get; set; }
    	
    	[DataMember] 		
        public string ProductRefName { get; set; }
    	
    	[DataMember] 		
        public string PapiroPrev { get; set; }
    
    	[DataMember]
        public virtual ICollection<ProductPart> ProductParts { get; set; }
    	[DataMember]
        public virtual ICollection<ProductTask> ProductTasks { get; set; }
    	[DataMember]
        public virtual ICollection<DocumentProduct> documentproducts { get; set; }
    	[DataMember]
        public virtual ICollection<ProductGraphLink> ProductGraphLinks { get; set; }
    	[DataMember]
        public virtual ICollection<Warehouse> WarehouseArticles { get; set; }
    }
}
