//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class ProductPart
    {
        public ProductPart()
        {
            this.ProductPartPrintableArticles = new HashSet<ProductPartsPrintableArticle>();
            this.ProductPartTasks = new HashSet<ProductPartTask>();
            this.ProductPartsToProductTasks = new HashSet<productpartstoproducttask>();
            this.CostDetails = new HashSet<CostDetail>();
            this.productpartprintings = new HashSet<ProductPartPrinting>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodProductPart { get; set; }
    	
    	[DataMember] 		
        public string CodProduct { get; set; }
    	
    	[DataMember] 		
        public string ProductPartName { get; set; }
    	
    	[DataMember] 		
        public string PrintingType { get; set; }
    	
    	[DataMember] 		
        public string Format { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> ServicesNumber { get; set; }
    	
    	[DataMember] 		
        public string CodProductPart_ { get; set; }
    	
    	[DataMember] 		
        public string FormatOpened { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> SubjectNumber { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> DCut { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> IsDCut { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> DCut1 { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> DCut2 { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> SideOnSide { get; set; }
    
    	[DataMember]
        public virtual Product Product { get; set; }
    	[DataMember]
        public virtual ICollection<ProductPartsPrintableArticle> ProductPartPrintableArticles { get; set; }
    	[DataMember]
        public virtual ICollection<ProductPartTask> ProductPartTasks { get; set; }
    	[DataMember]
        public virtual ICollection<productpartstoproducttask> ProductPartsToProductTasks { get; set; }
    	[DataMember]
        public virtual ICollection<CostDetail> CostDetails { get; set; }
    	[DataMember]
        public virtual ICollection<ProductPartPrinting> productpartprintings { get; set; }
    }
}
