//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPartTask
    {
        public System.DateTime TimeStampTable { get; set; }
        public string CodProductPartTask { get; set; }
        public string CodProductPart { get; set; }
        public string CodProductTask { get; set; }
    
        public virtual ProductPart ProductPart { get; set; }
        public virtual ProductTask ProductTask { get; set; }
    }
}
