//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class SemiRoll : Litho
    {
    	
    	[DataMember] 		
        public Nullable<long> PaperFirstStartLenght { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> Width2 { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> SemiRollWidth { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> PaperSecondStartLenght { get; set; }
    }
}
