//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class SheetPrintableArticleCuttedCost : SheetPrintableArticleCost
    {
    	
    	[DataMember] 		
        public Nullable<bool> UseTheSameCostOfPalletAfterKg { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseTheSameCostOfSheetAfterSheet { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> KgPallet { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> KgSheet { get; set; }
    }
}
