//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class State
    {
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodState { get; set; }
    	
    	[DataMember] 		
        public string StateName { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> StateNumber { get; set; }
    	
    	[DataMember] 		
        public string UsedIn { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseInEstimate { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseInOrder { get; set; }
    	
    	[DataMember] 		
        public string ResetLinkedStates { get; set; }
    }
}
