//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public abstract partial class TaskEstimatedOn
    {
        public TaskEstimatedOn()
        {
            this.steps = new HashSet<Step>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodTaskExecutor { get; set; }
    	
    	[DataMember] 		
        public string CodTaskEstimatedOn { get; set; }
    	
    	[DataMember] 		
        public string CostForfait { get; set; }
    	
    	[DataMember] 		
        public string CostForfaitForSheet { get; set; }
    	
    	[DataMember] 		
        public string CodOptionTypeOfTask { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> CostPerUnitBW { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseDifferentDeficitOnCostForWeightStepBW { get; set; }
    	
    	[DataMember] 		
        public string CostPerHourRunning { get; set; }
    	
    	[DataMember] 		
        public string CostPerHourStarting { get; set; }
    	
    	[DataMember] 		
        public Nullable<System.TimeSpan> WashingTime { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseDifferentCostPerUnit { get; set; }
    
    	[DataMember]
        public virtual TaskExecutor taskexecutors { get; set; }
    	[DataMember]
        public virtual ICollection<Step> steps { get; set; }
    	[DataMember]
        public virtual OptionTypeOfTask OptionTypeOfTask { get; set; }
    }
}
