//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public abstract partial class TaskEstimatedOnUnit : TaskEstimatedOn
    {
    	
    	[DataMember] 		
        public string CostPerUnit { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseDifferentCostPerUnit { get; set; }
    	
    	[DataMember] 		
        public string StartingCost1 { get; set; }
    	
    	[DataMember] 		
        public string StartingCost2 { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> UseDifferentDeficitOnCostForWeightStep { get; set; }
    }
}
