//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public abstract partial class TaskExecutor
    {
        public TaskExecutor()
        {
            this.SetTaskExecutorEstimatedOn = new HashSet<TaskEstimatedOn>();
            this.TypeOfTasks = new HashSet<TaskExecutorTypeOfTask>();
            this.costdetails = new HashSet<CostDetail>();
            this.TaskExecutorCylinders = new HashSet<TaskExecutorCylinder>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodTaskExecutor { get; set; }
    	
    	[DataMember] 		
        public string TaskExecutorName { get; set; }
    	
    	[DataMember] 		
        public string Version { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> Dismissed { get; set; }
    	
    	[DataMember] 		
        public string FormatMin { get; set; }
    	
    	[DataMember] 		
        public string FormatMax { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> WeightMin { get; set; }
    	
    	[DataMember] 		
        public Nullable<long> WeightMax { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> Pinza { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> ControPinza { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> Laterale { get; set; }
    	
    	[DataMember] 		
        public string CodTypeOfTask { get; set; }
    	
    	[DataMember] 		
        public string UniversalCodPapiro { get; set; }
    
    	[DataMember]
        public virtual ICollection<TaskEstimatedOn> SetTaskExecutorEstimatedOn { get; set; }
    	[DataMember]
        public virtual ICollection<TaskExecutorTypeOfTask> TypeOfTasks { get; set; }
    	[DataMember]
        public virtual TypeOfTask typeoftask_ { get; set; }
    	[DataMember]
        public virtual ICollection<CostDetail> costdetails { get; set; }
    	[DataMember]
        public virtual ICollection<TaskExecutorCylinder> TaskExecutorCylinders { get; set; }
    }
}
