//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskExecutorTypeOfTask
    {
        public System.DateTime TimeStampTable { get; set; }
        public string CodTaskExecutorTypeOfTask { get; set; }
        public string CodTypeOfTask { get; set; }
        public string CodTaskExecutor { get; set; }
    
        public virtual TaskExecutor TaskExecutor { get; set; }
        public virtual TypeOfTask TypeOfTask { get; set; }
    }
}
