//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class TypeOfBase
    {
        public TypeOfBase()
        {
            this.CustomerSupplierBases = new HashSet<CustomerSupplierBase>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodTypeOfBase { get; set; }
    	
    	[DataMember] 		
        public string BaseName { get; set; }
    
    	[DataMember]
        public virtual ICollection<CustomerSupplierBase> CustomerSupplierBases { get; set; }
    }
}
