//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class TypeOfTask
    {
        public TypeOfTask()
        {
            this.TaskExecutorTypeOfTasks = new HashSet<TaskExecutorTypeOfTask>();
            this.taskexecutors = new HashSet<TaskExecutor>();
            this.OptionTypeOfTasks = new HashSet<OptionTypeOfTask>();
        }
    
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodTypeOfTask { get; set; }
    	
    	[DataMember] 		
        public string TaskName { get; set; }
    	
    	[DataMember] 		
        public string CodCategoryOfTask { get; set; }
    
    	[DataMember]
        public virtual ICollection<TaskExecutorTypeOfTask> TaskExecutorTypeOfTasks { get; set; }
    	[DataMember]
        public virtual ICollection<TaskExecutor> taskexecutors { get; set; }
    	[DataMember]
        public virtual ICollection<OptionTypeOfTask> OptionTypeOfTasks { get; set; }
    }
}
