//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    	
    [DataContract] 
    public partial class WarehouseArticleMov
    {
    	
    	[DataMember] 		
        public System.DateTime TimeStampTable { get; set; }
    	
    	[DataMember] 		
        public string CodWarehouseArticleMov { get; set; }
    	
    	[DataMember] 		
        public string CodWarehouseArticle { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> Quantity { get; set; }
    	
    	[DataMember] 		
        public Nullable<int> TypeOfMov { get; set; }
    	
    	[DataMember] 		
        public string UnitOfMeasureMov { get; set; }
    	
    	[DataMember] 		
        public Nullable<double> UmConversion { get; set; }
    	
    	[DataMember] 		
        public Nullable<System.DateTime> Date { get; set; }
    	
    	[DataMember] 		
        public Nullable<bool> Used { get; set; }
    
    	[DataMember]
        public virtual Warehouse WarehouseArticle { get; set; }
    }
}
