//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Validation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Articolo.
        /// </summary>
        public static string ArticleName {
            get {
                return ResourceManager.GetString("ArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\b|\+|\-|)(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})*(\b|\%|)?$)|(^$).
        /// </summary>
        public static string AutoChangesValidation {
            get {
                return ResourceManager.GetString("AutoChangesValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire un&apos;espressione valita (tipo: +5% oppure -0,50 etc..).
        /// </summary>
        public static string AutoChangesValidationError {
            get {
                return ResourceManager.GetString("AutoChangesValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragione Sociale.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragione sociale del cliente o del fornitore.
        /// </summary>
        public static string BusinessNameToolTip {
            get {
                return ResourceManager.GetString("BusinessNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla Inserimento.
        /// </summary>
        public static string CancelAdd {
            get {
                return ResourceManager.GetString("CancelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Città.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Articolo.
        /// </summary>
        public static string CodArticle {
            get {
                return ResourceManager.GetString("CodArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Cliente/Fornitore.
        /// </summary>
        public static string CodCustomerSupplier {
            get {
                return ResourceManager.GetString("CodCustomerSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasciare vuoto se si vuole un codice cliente/fornitore automaticamente assegnato dal sistema.
        /// </summary>
        public static string CodCustomerSupplierToolTip {
            get {
                return ResourceManager.GetString("CodCustomerSupplierToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Fiscale.
        /// </summary>
        public static string CodiceFiscale {
            get {
                return ResourceManager.GetString("CodiceFiscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di Indirizzo.
        /// </summary>
        public static string CodTypeOfBaseDropDown {
            get {
                return ResourceManager.GetString("CodTypeOfBaseDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colore.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo al Kg.
        /// </summary>
        public static string CostPerKg {
            get {
                return ResourceManager.GetString("CostPerKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo al Metro lineare.
        /// </summary>
        public static string CostPerMl {
            get {
                return ResourceManager.GetString("CostPerMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo al Mq.
        /// </summary>
        public static string CostPerMq {
            get {
                return ResourceManager.GetString("CostPerMq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo al foglio.
        /// </summary>
        public static string CostPerSheet {
            get {
                return ResourceManager.GetString("CostPerSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo Unitario.
        /// </summary>
        public static string CostPerUnit {
            get {
                return ResourceManager.GetString("CostPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazione.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(\d{1,3}(\.\d{3})*|(\d+))(\,\d{0,5})?$)|(^$).
        /// </summary>
        public static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato valuta non valido (es. valido: 0,8756).
        /// </summary>
        public static string CurrencyValidationError {
            get {
                return ResourceManager.GetString("CurrencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inserire una mail valida.
        /// </summary>
        public static string EmailField {
            get {
                return ResourceManager.GetString("EmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato (cm x cm).
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mano.
        /// </summary>
        public static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kg.
        /// </summary>
        public static string Kg {
            get {
                return ResourceManager.GetString("Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kg.
        /// </summary>
        public static string KgPallet {
            get {
                return ResourceManager.GetString("KgPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fogli.
        /// </summary>
        public static string KgSheet {
            get {
                return ResourceManager.GetString("KgSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metri.
        /// </summary>
        public static string Ml {
            get {
                return ResourceManager.GetString("Ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mq minimali.
        /// </summary>
        public static string MqForafait {
            get {
                return ResourceManager.GetString("MqForafait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiale.
        /// </summary>
        public static string NameOfMaterial {
            get {
                return ResourceManager.GetString("NameOfMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No b/v.
        /// </summary>
        public static string NoBv {
            get {
                return ResourceManager.GetString("NoBv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pinza.
        /// </summary>
        public static string NoPinza {
            get {
                return ResourceManager.GetString("NoPinza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcune Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generico.
        /// </summary>
        public static string ObjectPrintableArticleType {
            get {
                return ResourceManager.GetString("ObjectPrintableArticleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsoleto.
        /// </summary>
        public static string Outdated {
            get {
                return ResourceManager.GetString("Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pec.
        /// </summary>
        public static string Pec {
            get {
                return ResourceManager.GetString("Pec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotolo.
        /// </summary>
        public static string PlotterRollType {
            get {
                return ResourceManager.GetString("PlotterRollType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigido.
        /// </summary>
        public static string PlotterSheetType {
            get {
                return ResourceManager.GetString("PlotterSheetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAP.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato Stampabile.
        /// </summary>
        public static string PrintableFormat {
            get {
                return ResourceManager.GetString("PrintableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocco.
        /// </summary>
        public static string ProductBlockSheetType {
            get {
                return ResourceManager.GetString("ProductBlockSheetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libro.
        /// </summary>
        public static string ProductBookSingleSheetType {
            get {
                return ResourceManager.GetString("ProductBookSingleSheetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singolo.
        /// </summary>
        public static string ProductSingleSheetType {
            get {
                return ResourceManager.GetString("ProductSingleSheetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referente.
        /// </summary>
        public static string Referee {
            get {
                return ResourceManager.GetString("Referee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richiesto per completare l&apos;operazione.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigido/Banner/Mq.
        /// </summary>
        public static string RigidPrintableArticleType {
            get {
                return ResourceManager.GetString("RigidPrintableArticleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo un campo tra  Costo al mq e Costo al Metro Lineare deve essere compilato.
        /// </summary>
        public static string RollPrintableArticheAutoChangesFieldValidationError {
            get {
                return ResourceManager.GetString("RollPrintableArticheAutoChangesFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotolo.
        /// </summary>
        public static string RollPrintableArticleType {
            get {
                return ResourceManager.GetString("RollPrintableArticleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotolo.
        /// </summary>
        public static string RollType {
            get {
                return ResourceManager.GetString("RollType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fogli a Pacco.
        /// </summary>
        public static string SheetPerPacked {
            get {
                return ResourceManager.GetString("SheetPerPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fogli a Pallet.
        /// </summary>
        public static string SheetPerPallet {
            get {
                return ResourceManager.GetString("SheetPerPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foglio.
        /// </summary>
        public static string SheetPrintableArticleType {
            get {
                return ResourceManager.GetString("SheetPrintableArticleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foglio.
        /// </summary>
        public static string SheetType {
            get {
                return ResourceManager.GetString("SheetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensione.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produttore.
        /// </summary>
        public static string SupplierMaker {
            get {
                return ResourceManager.GetString("SupplierMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornitore.
        /// </summary>
        public static string SupplierType {
            get {
                return ResourceManager.GetString("SupplierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornitore.
        /// </summary>
        public static string SupplyerBuy {
            get {
                return ResourceManager.GetString("SupplyerBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Fiscale.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il codice fiscale del cliente o del fornitore.
        /// </summary>
        public static string TaxCodeToolTip {
            get {
                return ResourceManager.GetString("TaxCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spessore.
        /// </summary>
        public static string Thikness {
            get {
                return ResourceManager.GetString("Thikness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di Materiale.
        /// </summary>
        public static string TypeOfMaterial {
            get {
                return ResourceManager.GetString("TypeOfMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unità di Misura.
        /// </summary>
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa il Costo a Pallet dopo un peso in Kg.
        /// </summary>
        public static string UseTheSameCostOfPalletAfterKg {
            get {
                return ResourceManager.GetString("UseTheSameCostOfPalletAfterKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa il Costo a Pallet dopo un numero di Fogli.
        /// </summary>
        public static string UseTheSameCostOfSheetAfterSheet {
            get {
                return ResourceManager.GetString("UseTheSameCostOfSheetAfterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa il Costo Standard dopo un peso in Kg..
        /// </summary>
        public static string UseTheSameCostOfStandardWidthAfterKg {
            get {
                return ResourceManager.GetString("UseTheSameCostOfStandardWidthAfterKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa il Costo Standard dopo &quot;x&quot; metri lineari.
        /// </summary>
        public static string UseTheSameCostOfStandardWidthAfterMl {
            get {
                return ResourceManager.GetString("UseTheSameCostOfStandardWidthAfterMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partita Iva.
        /// </summary>
        public static string VatNumber {
            get {
                return ResourceManager.GetString("VatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La partita iva del cliente o del fornitore è obbligatoria.
        /// </summary>
        public static string VatNumberToolTip {
            get {
                return ResourceManager.GetString("VatNumberToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr/mq.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larghezza.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
