//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapiroMVC.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TypeOfTaskAndCodTypeOfTask {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypeOfTaskAndCodTypeOfTask() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapiroMVC.Views.Shared.App_LocalResources.TypeOfTaskAndCodTypeOfTask", typeof(TypeOfTaskAndCodTypeOfTask).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoppiatura.
        /// </summary>
        public static string CodACCOPPIATURA {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoppiatura 1 lato.
        /// </summary>
        public static string CodACCOPPIATURA_1LATO {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA_1LATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoppiatura 2 lati.
        /// </summary>
        public static string CodACCOPPIATURA_2LATI {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA_2LATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoppiatura 3 lati.
        /// </summary>
        public static string CodACCOPPIATURA_3LATI {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA_3LATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accoppiatura.
        /// </summary>
        public static string CodACCOPPIATURA_NO {
            get {
                return ResourceManager.GetString("CodACCOPPIATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglio doppio.
        /// </summary>
        public static string CodCodTAGLIO_DOPPIO {
            get {
                return ResourceManager.GetString("CodCodTAGLIO_DOPPIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foro.
        /// </summary>
        public static string CodFORO {
            get {
                return ResourceManager.GetString("CodFORO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No foro.
        /// </summary>
        public static string CodFORO_NO {
            get {
                return ResourceManager.GetString("CodFORO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si foro.
        /// </summary>
        public static string CodFORO_SI {
            get {
                return ResourceManager.GetString("CodFORO_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fustellatura.
        /// </summary>
        public static string CodFUSTELLATURA {
            get {
                return ResourceManager.GetString("CodFUSTELLATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CodFUSTELLATURA_NO {
            get {
                return ResourceManager.GetString("CodFUSTELLATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string CodFUSTELLATURA_SI {
            get {
                return ResourceManager.GetString("CodFUSTELLATURA_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fustellatura.
        /// </summary>
        public static string CodFUSTELLATURAROTOLO {
            get {
                return ResourceManager.GetString("CodFUSTELLATURAROTOLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CodFUSTELLATURAROTOLO_NO {
            get {
                return ResourceManager.GetString("CodFUSTELLATURAROTOLO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string CodFUSTELLATURAROTOLO_SI {
            get {
                return ResourceManager.GetString("CodFUSTELLATURAROTOLO_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lllllllllllllll.
        /// </summary>
        public static string CodGrandeFormato {
            get {
                return ResourceManager.GetString("CodGrandeFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercalatura.
        /// </summary>
        public static string CodINTERCALATURA {
            get {
                return ResourceManager.GetString("CodINTERCALATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Copie.
        /// </summary>
        public static string CodINTERCALATURA_2COPIE {
            get {
                return ResourceManager.GetString("CodINTERCALATURA_2COPIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Copie.
        /// </summary>
        public static string CodINTERCALATURA_3COPIE {
            get {
                return ResourceManager.GetString("CodINTERCALATURA_3COPIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Copie.
        /// </summary>
        public static string CodINTERCALATURA_4COPIE {
            get {
                return ResourceManager.GetString("CodINTERCALATURA_4COPIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No intercalatura.
        /// </summary>
        public static string CodINTERCALATURA_NO {
            get {
                return ResourceManager.GetString("CodINTERCALATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piega.
        /// </summary>
        public static string CodPIEGA {
            get {
                return ResourceManager.GetString("CodPIEGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 ante.
        /// </summary>
        public static string CodPIEGA_2ANTE {
            get {
                return ResourceManager.GetString("CodPIEGA_2ANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 ante.
        /// </summary>
        public static string CodPIEGA_3ANTE {
            get {
                return ResourceManager.GetString("CodPIEGA_3ANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna Piega.
        /// </summary>
        public static string CodPIEGA_NO {
            get {
                return ResourceManager.GetString("CodPIEGA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastificatura.
        /// </summary>
        public static string CodPLASTIFICATURA {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucida 1 Lato.
        /// </summary>
        public static string CodPLASTIFICATURA_LUCIDA1 {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_LUCIDA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucida 2 Lati.
        /// </summary>
        public static string CodPLASTIFICATURA_LUCIDA2 {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_LUCIDA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna Plastificatura.
        /// </summary>
        public static string CodPLASTIFICATURA_NO {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaca 1 Lato.
        /// </summary>
        public static string CodPLASTIFICATURA_OPACA1 {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_OPACA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaca 2 Lati.
        /// </summary>
        public static string CodPLASTIFICATURA_OPACA2 {
            get {
                return ResourceManager.GetString("CodPLASTIFICATURA_OPACA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice .
        /// </summary>
        public static string CodProductCaption {
            get {
                return ResourceManager.GetString("CodProductCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegatura brossura.
        /// </summary>
        public static string CodRILEGATURA_BROSSURA {
            get {
                return ResourceManager.GetString("CodRILEGATURA_BROSSURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegatura brossura filorefe.
        /// </summary>
        public static string CodRILEGATURA_BROSSURA_FILOREFE {
            get {
                return ResourceManager.GetString("CodRILEGATURA_BROSSURA_FILOREFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegatuta gregata fresata.
        /// </summary>
        public static string CodRILEGATURA_BROSSURA_GREGATA_FRESATA {
            get {
                return ResourceManager.GetString("CodRILEGATURA_BROSSURA_GREGATA_FRESATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rilegatura brossura.
        /// </summary>
        public static string CodRILEGATURA_BROSSURA_NO {
            get {
                return ResourceManager.GetString("CodRILEGATURA_BROSSURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegatura punta metallica.
        /// </summary>
        public static string CodRILEGATURA_PM {
            get {
                return ResourceManager.GetString("CodRILEGATURA_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegatura a 2 punti metallici.
        /// </summary>
        public static string CodRILEGATURA_PM_2PUNTI {
            get {
                return ResourceManager.GetString("CodRILEGATURA_PM_2PUNTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rilegatura a punta metallica.
        /// </summary>
        public static string CodRILEGATURA_PM_NO {
            get {
                return ResourceManager.GetString("CodRILEGATURA_PM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilegatura spirale.
        /// </summary>
        public static string CodRILEGATURA_SPIRALE {
            get {
                return ResourceManager.GetString("CodRILEGATURA_SPIRALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rilegatura spirale.
        /// </summary>
        public static string CodRILEGATURA_SPIRALE_NO {
            get {
                return ResourceManager.GetString("CodRILEGATURA_SPIRALE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si rilegatura spirale.
        /// </summary>
        public static string CodRILEGATURA_SPIRALE_SI {
            get {
                return ResourceManager.GetString("CodRILEGATURA_SPIRALE_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilievo a secco.
        /// </summary>
        public static string CodRILIEVO_A_SECCO {
            get {
                return ResourceManager.GetString("CodRILIEVO_A_SECCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rilievo a secco.
        /// </summary>
        public static string CodRILIEVO_A_SECCO_NO {
            get {
                return ResourceManager.GetString("CodRILIEVO_A_SECCO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si rilevo a secco.
        /// </summary>
        public static string CodRILIEVO_A_SECCO_SI {
            get {
                return ResourceManager.GetString("CodRILIEVO_A_SECCO_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa Serigrafica 1 colore.
        /// </summary>
        public static string CodSERIGRAFIA_1 {
            get {
                return ResourceManager.GetString("CodSERIGRAFIA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa serigrafica 2 colori.
        /// </summary>
        public static string CodSERIGRAFIA_2 {
            get {
                return ResourceManager.GetString("CodSERIGRAFIA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa serigrafica 3 colori.
        /// </summary>
        public static string CodSERIGRAFIA_3 {
            get {
                return ResourceManager.GetString("CodSERIGRAFIA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna serigrafia.
        /// </summary>
        public static string CodSERIGRAFIA_NO {
            get {
                return ResourceManager.GetString("CodSERIGRAFIA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa Serigrafica.
        /// </summary>
        public static string CodSERIGRAFIA_SI {
            get {
                return ResourceManager.GetString("CodSERIGRAFIA_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serigrafia UV spessorata.
        /// </summary>
        public static string CodSERIGRAFIA_UVSPESSORATA {
            get {
                return ResourceManager.GetString("CodSERIGRAFIA_UVSPESSORATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa Serigrafica 1 colore.
        /// </summary>
        public static string CodSERIGRAFIAROTOLO_1 {
            get {
                return ResourceManager.GetString("CodSERIGRAFIAROTOLO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa serigrafica 2 colori.
        /// </summary>
        public static string CodSERIGRAFIAROTOLO_2 {
            get {
                return ResourceManager.GetString("CodSERIGRAFIAROTOLO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa serigrafica 3 colori.
        /// </summary>
        public static string CodSERIGRAFIAROTOLO_3 {
            get {
                return ResourceManager.GetString("CodSERIGRAFIAROTOLO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna serigrafia.
        /// </summary>
        public static string CodSERIGRAFIAROTOLO_NO {
            get {
                return ResourceManager.GetString("CodSERIGRAFIAROTOLO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa serigrafica.
        /// </summary>
        public static string CodSERIGRAFIAROTOLO_SI {
            get {
                return ResourceManager.GetString("CodSERIGRAFIAROTOLO_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serigrafia UV spessorata.
        /// </summary>
        public static string CodSERIGRAFIAROTOLO_UVSPESSORATA {
            get {
                return ResourceManager.GetString("CodSERIGRAFIAROTOLO_UVSPESSORATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa.
        /// </summary>
        public static string CodSTAMPA {
            get {
                return ResourceManager.GetString("CodSTAMPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa fronte retro in bianco e nero.
        /// </summary>
        public static string CodSTAMPA_FR_BN {
            get {
                return ResourceManager.GetString("CodSTAMPA_FR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa fronte retro a colori.
        /// </summary>
        public static string CodSTAMPA_FR_COL {
            get {
                return ResourceManager.GetString("CodSTAMPA_FR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa fronte in bianco e nero.
        /// </summary>
        public static string CodSTAMPA_FRONTE_BN {
            get {
                return ResourceManager.GetString("CodSTAMPA_FRONTE_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa fronte a colori.
        /// </summary>
        public static string CodSTAMPA_FRONTE_COL {
            get {
                return ResourceManager.GetString("CodSTAMPA_FRONTE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stampa.
        /// </summary>
        public static string CodSTAMPA_NO {
            get {
                return ResourceManager.GetString("CodSTAMPA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminazione.
        /// </summary>
        public static string CodSTAMPAACALDOROTOLO {
            get {
                return ResourceManager.GetString("CodSTAMPAACALDOROTOLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 colore.
        /// </summary>
        public static string CodSTAMPAACALDOROTOLO_1 {
            get {
                return ResourceManager.GetString("CodSTAMPAACALDOROTOLO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 colori.
        /// </summary>
        public static string CodSTAMPAACALDOROTOLO_2 {
            get {
                return ResourceManager.GetString("CodSTAMPAACALDOROTOLO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 colori.
        /// </summary>
        public static string CodSTAMPAACALDOROTOLO_3 {
            get {
                return ResourceManager.GetString("CodSTAMPAACALDOROTOLO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 colori.
        /// </summary>
        public static string CodSTAMPAACALDOROTOLO_4 {
            get {
                return ResourceManager.GetString("CodSTAMPAACALDOROTOLO_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna laminazione.
        /// </summary>
        public static string CodSTAMPAACALDOROTOLO_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAACALDOROTOLO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa digitale.
        /// </summary>
        public static string CodSTAMPADIGITALE {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro in bianco e nero.
        /// </summary>
        public static string CodSTAMPADIGITALE_FR_BN {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_FR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro a colori.
        /// </summary>
        public static string CodSTAMPADIGITALE_FR_COL {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_FR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte in bianco e nero.
        /// </summary>
        public static string CodSTAMPADIGITALE_FRONTE_BN {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_FRONTE_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte a colori.
        /// </summary>
        public static string CodSTAMPADIGITALE_FRONTE_COL {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_FRONTE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPADIGITALE_NO {
            get {
                return ResourceManager.GetString("CodSTAMPADIGITALE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 colore.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_1 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 colore e retro.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_1RETRO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_1RETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_2 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 colori e retro.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_2RETRO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_2RETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_3 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 colori e retro.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_3RETRO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_3RETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_4 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 colori e retro.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_4RETRO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_4RETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_5 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 colori e retro.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_5RETRO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_5RETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 colori.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_6 {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 colori e retro.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_6RETRO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_6RETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nessuna stampa.
        /// </summary>
        public static string CodSTAMPAETICHROTOLO_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAETICHROTOLO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV alta qualità.
        /// </summary>
        public static string CodSTAMPAMORBIDO_ALTA {
            get {
                return ResourceManager.GetString("CodSTAMPAMORBIDO_ALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV bassa qualità.
        /// </summary>
        public static string CodSTAMPAMORBIDO_BASSA {
            get {
                return ResourceManager.GetString("CodSTAMPAMORBIDO_BASSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV media qualità.
        /// </summary>
        public static string CodSTAMPAMORBIDO_MEDIA {
            get {
                return ResourceManager.GetString("CodSTAMPAMORBIDO_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPAMORBIDO_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAMORBIDO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa offset.
        /// </summary>
        public static string CodSTAMPAOFF {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro in bianco e nero.
        /// </summary>
        public static string CodSTAMPAOFF_FR_BN {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_FR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro a colori.
        /// </summary>
        public static string CodSTAMPAOFF_FR_COL {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_FR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte in bianco e nero.
        /// </summary>
        public static string CodSTAMPAOFF_FRONTE_BN {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_FRONTE_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte a colori.
        /// </summary>
        public static string CodSTAMPAOFF_FRONTE_COL {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_FRONTE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPAOFF_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAOFF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa offset o digitale.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro in bianco e nero.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_FR_BN {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_FR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte retro a colori.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_FR_COL {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_FR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte in bianco e nero.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_FRONTE_BN {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_FRONTE_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa fronte a colori.
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_FRONTE_COL {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_FRONTE_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPAOFFeDIGITALE_NO {
            get {
                return ResourceManager.GetString("CodSTAMPAOFFeDIGITALE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa Materiale Rigido.
        /// </summary>
        public static string CodSTAMPARIGIDO {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV alta qualità.
        /// </summary>
        public static string CodSTAMPARIGIDO_ALTA {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_ALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV alta qualità Day/Night.
        /// </summary>
        public static string CodSTAMPARIGIDO_ALTADN {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_ALTADN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV alta qualità e bianco.
        /// </summary>
        public static string CodSTAMPARIGIDO_ALTAW {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_ALTAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV bassa qualità.
        /// </summary>
        public static string CodSTAMPARIGIDO_BASSA {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_BASSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV bassa qualità Day/Night.
        /// </summary>
        public static string CodSTAMPARIGIDO_BASSADN {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_BASSADN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV bassa qualità e bianco.
        /// </summary>
        public static string CodSTAMPARIGIDO_BASSAW {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_BASSAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV media qualità.
        /// </summary>
        public static string CodSTAMPARIGIDO_MEDIA {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV media qualità Day/Night.
        /// </summary>
        public static string CodSTAMPARIGIDO_MEDIADN {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_MEDIADN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa UV media qualità e bianco.
        /// </summary>
        public static string CodSTAMPARIGIDO_MEDIAW {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_MEDIAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodSTAMPARIGIDO_NO {
            get {
                return ResourceManager.GetString("CodSTAMPARIGIDO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglio.
        /// </summary>
        public static string CodTAGLIO {
            get {
                return ResourceManager.GetString("CodTAGLIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglio al vivo.
        /// </summary>
        public static string CodTAGLIO_AL_VIVO {
            get {
                return ResourceManager.GetString("CodTAGLIO_AL_VIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No taglio.
        /// </summary>
        public static string CodTAGLIO_NO {
            get {
                return ResourceManager.GetString("CodTAGLIO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna verniciatura.
        /// </summary>
        public static string CodTAVOLOCONTROLLO_NO {
            get {
                return ResourceManager.GetString("CodTAVOLOCONTROLLO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavolo di controllo.
        /// </summary>
        public static string CodTAVOLOCONTROLLO_SI {
            get {
                return ResourceManager.GetString("CodTAVOLOCONTROLLO_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verniciatura.
        /// </summary>
        public static string CodVERNICIATURA {
            get {
                return ResourceManager.GetString("CodVERNICIATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucida 1 Lato.
        /// </summary>
        public static string CodVERNICIATURA_LUCIDA1 {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_LUCIDA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucida 2 Lati.
        /// </summary>
        public static string CodVERNICIATURA_LUCIDA2 {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_LUCIDA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna verniciatura.
        /// </summary>
        public static string CodVERNICIATURA_NO {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaca 1 Lato.
        /// </summary>
        public static string CodVERNICIATURA_OPACA1 {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_OPACA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaca 2 Lati.
        /// </summary>
        public static string CodVERNICIATURA_OPACA2 {
            get {
                return ResourceManager.GetString("CodVERNICIATURA_OPACA2", resourceCulture);
            }
        }
    }
}
